



```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- drs.par.poly[,c("A.drs", "B1.drs", "B2.drs", "B3.drs")]
drs.info.poly <- hoo %>%
  mutate(p1.0 = 1,
         p2.0 = 1,
         p3.0 = 1,
         p4.0 = 1,
         p5.0 = 1,
         p6.0 = 1,
         p7.0 = 1,
         p8.0 = 1,
         p9.0 = 1,
         p10.0 = 1,
         p11.0 = 1,
         p12.0 = 1,
         p13.0 = 1,
         p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p6.1 = (exp(my.par[6,1]*(theta-my.par[6,2]))/(1+exp(my.par[6,1]*(theta-my.par[6,2])))),
         p7.1 = (exp(my.par[7,1]*(theta-my.par[7,2]))/(1+exp(my.par[7,1]*(theta-my.par[7,2])))),
         p8.1 = (exp(my.par[8,1]*(theta-my.par[8,2]))/(1+exp(my.par[8,1]*(theta-my.par[8,2])))),
         p9.1 = (exp(my.par[9,1]*(theta-my.par[9,2]))/(1+exp(my.par[9,1]*(theta-my.par[9,2])))),
         p10.1 = (exp(my.par[10,1]*(theta-my.par[10,2]))/(1+exp(my.par[10,1]*(theta-my.par[10,2])))),
         p11.1 = (exp(my.par[11,1]*(theta-my.par[11,2]))/(1+exp(my.par[11,1]*(theta-my.par[11,2])))),
         p12.1 = (exp(my.par[12,1]*(theta-my.par[12,2]))/(1+exp(my.par[12,1]*(theta-my.par[12,2])))),
         p13.1 = (exp(my.par[13,1]*(theta-my.par[13,2]))/(1+exp(my.par[13,1]*(theta-my.par[13,2])))),
         p1.2 = (exp(my.par[1,1]*(theta-my.par[1,3]))/(1+exp(my.par[1,1]*(theta-my.par[1,3])))),
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = (exp(my.par[4,1]*(theta-my.par[4,3]))/(1+exp(my.par[4,1]*(theta-my.par[4,3])))),
         p5.2 = (exp(my.par[5,1]*(theta-my.par[5,3]))/(1+exp(my.par[5,1]*(theta-my.par[5,3])))),
         p6.2 = (exp(my.par[6,1]*(theta-my.par[6,3]))/(1+exp(my.par[6,1]*(theta-my.par[6,3])))),
         p7.2 = (exp(my.par[7,1]*(theta-my.par[7,3]))/(1+exp(my.par[7,1]*(theta-my.par[7,3])))),
         p8.2 = (exp(my.par[8,1]*(theta-my.par[8,3]))/(1+exp(my.par[8,1]*(theta-my.par[8,3])))),
         p9.2 = (exp(my.par[9,1]*(theta-my.par[9,3]))/(1+exp(my.par[9,1]*(theta-my.par[9,3])))),
         p10.2 = (exp(my.par[10,1]*(theta-my.par[10,3]))/(1+exp(my.par[10,1]*(theta-my.par[10,3])))),
         p11.2 = (exp(my.par[11,1]*(theta-my.par[11,3]))/(1+exp(my.par[11,1]*(theta-my.par[11,3])))),
         p12.2 = (exp(my.par[12,1]*(theta-my.par[12,3]))/(1+exp(my.par[12,1]*(theta-my.par[12,3])))),
         p13.2 = (exp(my.par[13,1]*(theta-my.par[13,3]))/(1+exp(my.par[13,1]*(theta-my.par[13,3])))),
         p1.3 = (exp(my.par[1,1]*(theta-my.par[1,4]))/(1+exp(my.par[1,1]*(theta-my.par[1,4])))),
         p2.3 = (exp(my.par[2,1]*(theta-my.par[2,4]))/(1+exp(my.par[2,1]*(theta-my.par[2,4])))),
         p3.3 = (exp(my.par[3,1]*(theta-my.par[3,4]))/(1+exp(my.par[3,1]*(theta-my.par[3,4])))),
         p4.3 = 0,
         p5.3 = (exp(my.par[5,1]*(theta-my.par[5,4]))/(1+exp(my.par[5,1]*(theta-my.par[5,4])))),
         p6.3 = (exp(my.par[6,1]*(theta-my.par[6,4]))/(1+exp(my.par[6,1]*(theta-my.par[6,4])))),
         p7.3 = 0,
         p8.3 = 0,
         p9.3 = (exp(my.par[9,1]*(theta-my.par[9,4]))/(1+exp(my.par[9,1]*(theta-my.par[9,4])))),
         p10.3 = (exp(my.par[10,1]*(theta-my.par[10,4]))/(1+exp(my.par[10,1]*(theta-my.par[10,4])))),
         p11.3 = (exp(my.par[11,1]*(theta-my.par[11,4]))/(1+exp(my.par[11,1]*(theta-my.par[11,4])))),
         p12.3 = (exp(my.par[12,1]*(theta-my.par[12,4]))/(1+exp(my.par[12,1]*(theta-my.par[12,4])))),
         p13.3 = (exp(my.par[13,1]*(theta-my.par[13,4]))/(1+exp(my.par[13,1]*(theta-my.par[13,4])))),   
         p1.4 = 0,
         p2.4 = 0,
         p3.4 = 0,
         p5.4 = 0,
         p6.4 = 0,
         p9.4 = 0,
         p10.4 = 0,
         p11.4 = 0,
         p12.4 = 0,
         p13.4 = 0,
         i1 = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) +
                                 ((p1.1*(1-p1.1)) - (p1.2*(1-p1.2)))^2/(p1.1-p1.2) +
                                 ((p1.2*(1-p1.2)) - (p1.3*(1-p1.3)))^2/(p1.2-p1.3) +
                                 ((p1.3*(1-p1.3)) - (p1.4*(1-p1.4)))^2/(p1.3-p1.4)),
         i2 = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                 ((p2.1*(1-p2.1)) - (p2.2*(1-p2.2)))^2/(p2.1-p2.2) +
                                 ((p2.2*(1-p2.2)) - (p2.3*(1-p2.3)))^2/(p2.2-p2.3) +
                                 ((p2.3*(1-p2.3)) - (p2.4*(1-p2.4)))^2/(p2.3-p2.4)),
         i3 = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                 ((p3.1*(1-p3.1)) - (p3.2*(1-p3.2)))^2/(p3.1-p3.2) +
                                 ((p3.2*(1-p3.2)) - (p3.3*(1-p3.3)))^2/(p3.2-p3.3) +
                                 ((p3.3*(1-p3.3)) - (p3.4*(1-p3.4)))^2/(p3.3-p3.4)),
         i4 = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                 ((p4.1*(1-p4.1)) - (p4.2*(1-p4.2)))^2/(p4.1-p4.2) +
                                 ((p4.2*(1-p4.2)) - (p4.3*(1-p4.3)))^2/(p4.2-p4.3)),         
         i5 = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                 ((p5.1*(1-p5.1)) - (p5.2*(1-p5.2)))^2/(p5.1-p5.2) +
                                 ((p5.2*(1-p5.2)) - (p5.3*(1-p5.3)))^2/(p5.2-p5.3) +
                                 ((p5.3*(1-p5.3)) - (p5.4*(1-p5.4)))^2/(p5.3-p5.4)),
         i6 = my.par[6,1]^2 * (  ((p6.0*(1-p6.0)) - (p6.1*(1-p6.1)))^2/(p6.0-p6.1) +
                                 ((p6.1*(1-p6.1)) - (p6.2*(1-p6.2)))^2/(p6.1-p6.2) +
                                 ((p6.2*(1-p6.2)) - (p6.3*(1-p6.3)))^2/(p6.2-p6.3) +
                                 ((p6.3*(1-p6.3)) - (p6.4*(1-p6.4)))^2/(p6.3-p6.4)),
         i7 = my.par[7,1]^2 * (  ((p7.0*(1-p7.0)) - (p7.1*(1-p7.1)))^2/(p7.0-p7.1) +
                                 ((p7.1*(1-p7.1)) - (p7.2*(1-p7.2)))^2/(p7.1-p7.2) +
                                 ((p7.2*(1-p7.2)) - (p7.3*(1-p7.3)))^2/(p7.2-p7.3)),
         i8 = my.par[8,1]^2 * (  ((p8.0*(1-p8.0)) - (p8.1*(1-p8.1)))^2/(p8.0-p8.1) +
                                 ((p8.1*(1-p8.1)) - (p8.2*(1-p8.2)))^2/(p8.1-p8.2) +
                                 ((p8.2*(1-p8.2)) - (p8.3*(1-p8.3)))^2/(p8.2-p8.3)),         
         i9 = my.par[9,1]^2 * (  ((p9.0*(1-p9.0)) - (p9.1*(1-p9.1)))^2/(p9.0-p9.1) +
                                 ((p9.1*(1-p9.1)) - (p9.2*(1-p9.2)))^2/(p9.1-p9.2) +
                                 ((p9.2*(1-p9.2)) - (p9.3*(1-p9.3)))^2/(p9.2-p9.3) +
                                 ((p9.3*(1-p9.3)) - (p9.4*(1-p9.4)))^2/(p9.3-p9.4)),
         i10 = my.par[10,1]^2 * (  ((p10.0*(1-p10.0)) - (p10.1*(1-p10.1)))^2/(p10.0-p10.1) +
                                   ((p10.1*(1-p10.1)) - (p10.2*(1-p10.2)))^2/(p10.1-p10.2) +
                                   ((p10.2*(1-p10.2)) - (p10.3*(1-p10.3)))^2/(p10.2-p10.3) +
                                   ((p10.3*(1-p10.3)) - (p10.4*(1-p10.4)))^2/(p10.3-p10.4)),
         i11 = my.par[11,1]^2 * (  ((p11.0*(1-p11.0)) - (p11.1*(1-p11.1)))^2/(p11.0-p11.1) +
                                   ((p11.1*(1-p11.1)) - (p11.2*(1-p11.2)))^2/(p11.1-p11.2) +
                                   ((p11.2*(1-p11.2)) - (p11.3*(1-p11.3)))^2/(p11.2-p11.3) +
                                   ((p11.3*(1-p11.3)) - (p11.4*(1-p11.4)))^2/(p11.3-p11.4)),
         i12 = my.par[12,1]^2 * (  ((p12.0*(1-p12.0)) - (p12.1*(1-p12.1)))^2/(p12.0-p12.1) +
                                   ((p12.1*(1-p12.1)) - (p12.2*(1-p12.2)))^2/(p12.1-p12.2) +
                                   ((p12.2*(1-p12.2)) - (p12.3*(1-p12.3)))^2/(p12.2-p12.3) +
                                   ((p12.3*(1-p12.3)) - (p12.4*(1-p12.4)))^2/(p12.3-p12.4)),
         i13 = my.par[13,1]^2 * (  ((p13.0*(1-p13.0)) - (p13.1*(1-p13.1)))^2/(p13.0-p13.1) +
                                   ((p13.1*(1-p13.1)) - (p13.2*(1-p13.2)))^2/(p13.1-p13.2) +
                                   ((p13.2*(1-p13.2)) - (p13.3*(1-p13.3)))^2/(p13.2-p13.3) +
                                   ((p13.3*(1-p13.3)) - (p13.4*(1-p13.4)))^2/(p13.3-p13.4)),
         es1 = p1.1 + p1.2 + p1.3, 
         es2 = p2.1 + p2.2 + p2.3, 
         es3 = p3.1 + p3.2 + p3.3, 
         es4 = p4.1 + p4.2, 
         es5 = p5.1 + p5.2 + p5.3, 
         es6 = p6.1 + p6.2 + p6.3, 
         es7 = p7.1 + p7.2, 
         es8 = p8.1 + p8.2, 
         es9 = p9.1 + p9.2 + p9.3, 
         es10 = p10.1 + p10.2 + p10.3, 
         es11 = p11.1 + p11.2 + p11.3, 
         es12 = p12.1 + p12.2 + p12.3, 
         es13 = p13.1 + p13.2 + p13.3, 
         i1.sens = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) +
                                      ((p1.1*(1-p1.1)) - (p1.4*(1-p1.4)))^2/(p1.1-p1.4)),
         i2.sens = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                      ((p2.1*(1-p2.1)) - (p2.4*(1-p2.4)))^2/(p2.1-p2.4)),
         i3.sens = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                      ((p3.1*(1-p3.1)) - (p3.4*(1-p3.4)))^2/(p3.1-p3.4)),
         i4.sens = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                      ((p4.1*(1-p4.1)) - (p4.3*(1-p4.3)))^2/(p4.1-p4.3)),         
         i5.sens = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                      ((p5.1*(1-p5.1)) - (p5.4*(1-p5.4)))^2/(p5.1-p5.4)),
         i6.sens = my.par[6,1]^2 * (  ((p6.0*(1-p6.0)) - (p6.1*(1-p6.1)))^2/(p6.0-p6.1) +
                                      ((p6.1*(1-p6.1)) - (p6.4*(1-p6.4)))^2/(p6.1-p6.4)),
         i7.sens = my.par[7,1]^2 * (  ((p7.0*(1-p7.0)) - (p7.1*(1-p7.1)))^2/(p7.0-p7.1) +
                                      ((p7.1*(1-p7.1)) - (p7.3*(1-p7.3)))^2/(p7.1-p7.3)),
         i8.sens = my.par[8,1]^2 * (  ((p8.0*(1-p8.0)) - (p8.1*(1-p8.1)))^2/(p8.0-p8.1) +
                                      ((p8.1*(1-p8.1)) - (p8.3*(1-p8.3)))^2/(p8.1-p8.3)),         
         i9.sens = my.par[9,1]^2 * (  ((p9.0*(1-p9.0)) - (p9.1*(1-p9.1)))^2/(p9.0-p9.1) +
                                      ((p9.1*(1-p9.1)) - (p9.4*(1-p9.4)))^2/(p9.1-p9.4)),
         i10.sens = my.par[10,1]^2 * (  ((p10.0*(1-p10.0)) - (p10.1*(1-p10.1)))^2/(p10.0-p10.1) +
                                        ((p10.1*(1-p10.1)) - (p10.4*(1-p10.4)))^2/(p10.1-p10.4)),
         i11.sens = my.par[11,1]^2 * (  ((p11.0*(1-p11.0)) - (p11.1*(1-p11.1)))^2/(p11.0-p11.1) +
                                        ((p11.1*(1-p11.1)) - (p11.4*(1-p11.4)))^2/(p11.1-p11.4)),
         i12.sens = my.par[12,1]^2 * (  ((p12.0*(1-p12.0)) - (p12.1*(1-p12.1)))^2/(p12.0-p12.1) +
                                        ((p12.1*(1-p12.1)) - (p12.4*(1-p12.4)))^2/(p12.1-p12.4)),
         i13.sens = my.par[13,1]^2 * (  ((p13.0*(1-p13.0)) - (p13.1*(1-p13.1)))^2/(p13.0-p13.1) +
                                        ((p13.1*(1-p13.1)) - (p13.4*(1-p13.4)))^2/(p13.1-p13.4)),
         testscore = es1 + es2 + es3 + es4 + es5 + es6 + es7 + es8 + es9 + es10 + es11 + es12 + es13,
         info = i1 + i2 + i3 + i4 + i5 + i6 + i7 + i8 + i9 + i10 + i11 + i12 + i13,
         info.sens = i1.sens + i2.sens + i3.sens + i4.sens + i5.sens + i6.sens + i7.sens + 
           i8.sens + i9.sens + i10.sens + i11.sens + i12.sens + i13.sens,
         info.diff = info - info.sens,
         sem = info^(-.5),
         sem.sens = info.sens^(-.5))

```


```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- mdas.par.poly[,c("A.mdas", "B1.mdas", "B2.mdas", "B3.mdas")]
mdas.info.poly <- hoo %>%
  mutate(p1.0 = 1,
         p2.0 = 1,
         p3.0 = 1,
         p4.0 = 1,
         p5.0 = 1,
         p6.0 = 1,
         p7.0 = 1,
         p8.0 = 1,
         p9.0 = 1,
         p10.0 = 1,
         p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p6.1 = (exp(my.par[6,1]*(theta-my.par[6,2]))/(1+exp(my.par[6,1]*(theta-my.par[6,2])))),
         p7.1 = (exp(my.par[7,1]*(theta-my.par[7,2]))/(1+exp(my.par[7,1]*(theta-my.par[7,2])))),
         p8.1 = (exp(my.par[8,1]*(theta-my.par[8,2]))/(1+exp(my.par[8,1]*(theta-my.par[8,2])))),
         p9.1 = (exp(my.par[9,1]*(theta-my.par[9,2]))/(1+exp(my.par[9,1]*(theta-my.par[9,2])))),
         p10.1 = (exp(my.par[10,1]*(theta-my.par[10,2]))/(1+exp(my.par[10,1]*(theta-my.par[10,2])))),
         p1.2 = (exp(my.par[1,1]*(theta-my.par[1,3]))/(1+exp(my.par[1,1]*(theta-my.par[1,3])))),
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = (exp(my.par[4,1]*(theta-my.par[4,3]))/(1+exp(my.par[4,1]*(theta-my.par[4,3])))),
         p5.2 = (exp(my.par[5,1]*(theta-my.par[5,3]))/(1+exp(my.par[5,1]*(theta-my.par[5,3])))),
         p6.2 = (exp(my.par[6,1]*(theta-my.par[6,3]))/(1+exp(my.par[6,1]*(theta-my.par[6,3])))),
         p7.2 = (exp(my.par[7,1]*(theta-my.par[7,3]))/(1+exp(my.par[7,1]*(theta-my.par[7,3])))),
         p8.2 = (exp(my.par[8,1]*(theta-my.par[8,3]))/(1+exp(my.par[8,1]*(theta-my.par[8,3])))),
         p9.2 = (exp(my.par[9,1]*(theta-my.par[9,3]))/(1+exp(my.par[9,1]*(theta-my.par[9,3])))),
         p10.2 = (exp(my.par[10,1]*(theta-my.par[10,3]))/(1+exp(my.par[10,1]*(theta-my.par[10,3])))),
         p1.3 = 0,
         p2.3 = (exp(my.par[2,1]*(theta-my.par[2,4]))/(1+exp(my.par[2,1]*(theta-my.par[2,4])))),
         p3.3 = (exp(my.par[3,1]*(theta-my.par[3,4]))/(1+exp(my.par[3,1]*(theta-my.par[3,4])))),
         p4.3 = (exp(my.par[4,1]*(theta-my.par[4,4]))/(1+exp(my.par[4,1]*(theta-my.par[4,4])))),
         p5.3 = (exp(my.par[5,1]*(theta-my.par[5,4]))/(1+exp(my.par[5,1]*(theta-my.par[5,4])))),
         p6.3 = (exp(my.par[6,1]*(theta-my.par[6,4]))/(1+exp(my.par[6,1]*(theta-my.par[6,4])))),
         p7.3 = (exp(my.par[7,1]*(theta-my.par[7,4]))/(1+exp(my.par[7,1]*(theta-my.par[7,4])))),
         p8.3 = (exp(my.par[8,1]*(theta-my.par[8,4]))/(1+exp(my.par[8,1]*(theta-my.par[8,4])))),
         p9.3 = 0,
         p10.3 = (exp(my.par[10,1]*(theta-my.par[10,4]))/(1+exp(my.par[10,1]*(theta-my.par[10,4])))),
         p2.4 = 0,
         p3.4 = 0,
         p4.4 = 0,
         p5.4 = 0,
         p6.4 = 0,
         p7.4 = 0,
         p8.4 = 0,
         p10.4 = 0,
         i1 = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) +
                                 ((p1.1*(1-p1.1)) - (p1.2*(1-p1.2)))^2/(p1.1-p1.2) +
                                 ((p1.2*(1-p1.2)) - (p1.3*(1-p1.3)))^2/(p1.2-p1.3)),
         i2 = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                 ((p2.1*(1-p2.1)) - (p2.2*(1-p2.2)))^2/(p2.1-p2.2) +
                                 ((p2.2*(1-p2.2)) - (p2.3*(1-p2.3)))^2/(p2.2-p2.3) +
                                 ((p2.3*(1-p2.3)) - (p2.4*(1-p2.4)))^2/(p2.3-p2.4)),
         i3 = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                 ((p3.1*(1-p3.1)) - (p3.2*(1-p3.2)))^2/(p3.1-p3.2) +
                                 ((p3.2*(1-p3.2)) - (p3.3*(1-p3.3)))^2/(p3.2-p3.3) +
                                 ((p3.3*(1-p3.3)) - (p3.4*(1-p3.4)))^2/(p3.3-p3.4)),
         i4 = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                 ((p4.1*(1-p4.1)) - (p4.2*(1-p4.2)))^2/(p4.1-p4.2) +
                                 ((p4.2*(1-p4.2)) - (p4.3*(1-p4.3)))^2/(p4.2-p4.3) +
                                 ((p4.3*(1-p4.3)) - (p4.4*(1-p4.4)))^2/(p4.3-p4.4)),
         i5 = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                 ((p5.1*(1-p5.1)) - (p5.2*(1-p5.2)))^2/(p5.1-p5.2) +
                                 ((p5.2*(1-p5.2)) - (p5.3*(1-p5.3)))^2/(p5.2-p5.3) +
                                 ((p5.3*(1-p5.3)) - (p5.4*(1-p5.4)))^2/(p5.3-p5.4)),
         i6 = my.par[6,1]^2 * (  ((p6.0*(1-p6.0)) - (p6.1*(1-p6.1)))^2/(p6.0-p6.1) +
                                 ((p6.1*(1-p6.1)) - (p6.2*(1-p6.2)))^2/(p6.1-p6.2) +
                                 ((p6.2*(1-p6.2)) - (p6.3*(1-p6.3)))^2/(p6.2-p6.3) +
                                 ((p6.3*(1-p6.3)) - (p6.4*(1-p6.4)))^2/(p6.3-p6.4)),
         i7 = my.par[7,1]^2 * (  ((p7.0*(1-p7.0)) - (p7.1*(1-p7.1)))^2/(p7.0-p7.1) +
                                 ((p7.1*(1-p7.1)) - (p7.2*(1-p7.2)))^2/(p7.1-p7.2) +
                                 ((p7.2*(1-p7.2)) - (p7.3*(1-p7.3)))^2/(p7.2-p7.3) +
                                 ((p7.3*(1-p7.3)) - (p7.4*(1-p7.4)))^2/(p7.3-p7.4)),
         i8 = my.par[8,1]^2 * (  ((p8.0*(1-p8.0)) - (p8.1*(1-p8.1)))^2/(p8.0-p8.1) +
                                 ((p8.1*(1-p8.1)) - (p8.2*(1-p8.2)))^2/(p8.1-p8.2) +
                                 ((p8.2*(1-p8.2)) - (p8.3*(1-p8.3)))^2/(p8.2-p8.3) +
                                 ((p8.3*(1-p8.3)) - (p8.4*(1-p8.4)))^2/(p8.3-p8.4)),
         i9 = my.par[9,1]^2 * (  ((p9.0*(1-p9.0)) - (p9.1*(1-p9.1)))^2/(p9.0-p9.1) +
                                 ((p9.1*(1-p9.1)) - (p9.2*(1-p9.2)))^2/(p9.1-p9.2) +
                                 ((p9.2*(1-p9.2)) - (p9.3*(1-p9.3)))^2/(p9.2-p9.3)),
         i10 = my.par[10,1]^2 * (  ((p10.0*(1-p10.0)) - (p10.1*(1-p10.1)))^2/(p10.0-p10.1) +
                                   ((p10.1*(1-p10.1)) - (p10.2*(1-p10.2)))^2/(p10.1-p10.2) +
                                   ((p10.2*(1-p10.2)) - (p10.3*(1-p10.3)))^2/(p10.2-p10.3) +
                                   ((p10.3*(1-p10.3)) - (p10.4*(1-p10.4)))^2/(p10.3-p10.4)),
         es1 = p1.1 + p1.2, 
         es2 = p2.1 + p2.2 + p2.3, 
         es3 = p3.1 + p3.2 + p3.3, 
         es4 = p4.1 + p4.2 + p4.3, 
         es5 = p5.1 + p5.2 + p5.3, 
         es6 = p6.1 + p6.2 + p6.3, 
         es7 = p7.1 + p7.2 + p7.3, 
         es8 = p8.1 + p8.2 + p8.3, 
         es9 = p9.1 + p9.2, 
         es10 = p10.1 + p10.2 + p10.3, 
         i1.sens = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) +
                                      ((p1.1*(1-p1.1)) - (p1.3*(1-p1.3)))^2/(p1.1-p1.3)),
         i2.sens = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                      ((p2.1*(1-p2.1)) - (p2.4*(1-p2.4)))^2/(p2.1-p2.4)),
         i3.sens = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) + 
                                      ((p3.1*(1-p3.1)) - (p3.4*(1-p3.4)))^2/(p3.1-p3.4)),
         i4.sens = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                      ((p4.1*(1-p4.1)) - (p4.4*(1-p4.4)))^2/(p4.1-p4.4)),
         i5.sens = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                      ((p5.1*(1-p5.1)) - (p5.4*(1-p5.4)))^2/(p5.1-p5.4)),
         i6.sens = my.par[6,1]^2 * (  ((p6.0*(1-p6.0)) - (p6.1*(1-p6.1)))^2/(p6.0-p6.1) +
                                      ((p6.1*(1-p6.1)) - (p6.4*(1-p6.4)))^2/(p6.1-p6.4)),
         i7.sens = my.par[7,1]^2 * (  ((p7.0*(1-p7.0)) - (p7.1*(1-p7.1)))^2/(p7.0-p7.1) +
                                      ((p7.1*(1-p7.1)) - (p7.4*(1-p7.4)))^2/(p7.1-p7.4)),
         i8.sens = my.par[8,1]^2 * (  ((p8.0*(1-p8.0)) - (p8.1*(1-p8.1)))^2/(p8.0-p8.1) +
                                      ((p8.1*(1-p8.1)) - (p8.4*(1-p8.4)))^2/(p8.1-p8.4)),
         i9.sens = my.par[9,1]^2 * (  ((p9.0*(1-p9.0)) - (p9.1*(1-p9.1)))^2/(p9.0-p9.1) +
                                      ((p9.1*(1-p9.1)) - (p9.3*(1-p9.3)))^2/(p9.1-p9.3)),
         i10.sens = my.par[10,1]^2 * (  ((p10.0*(1-p10.0)) - (p10.1*(1-p10.1)))^2/(p10.0-p10.1) +
                                        ((p10.1*(1-p10.1)) - (p10.4*(1-p10.4)))^2/(p10.1-p10.4)),
         testscore = es1 + es2 + es3 + es4 + es5 + es6 + es7 + es8 + es9 + es10,
         info = i1 + i2 + i3 + i4 + i5 + i6 + i7 + i8 + i9 + i10,
         info.sens = i1.sens + i2.sens + i3.sens + i4.sens + i5.sens + i6.sens + 
           i7.sens + i8.sens + i9.sens + i10.sens,
         info.diff = info - info.sens,
         sem = info^(-.5),
         sem.sens = info.sens^(-.5))

```


```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- cam.par.poly[,c("A.cam", "B1.cam", "B2.cam")]
camlf.info.poly <- hoo %>%
  mutate(p1.0 = 1,
         p2.0 = 1,
         p3.0 = 1,
         p4.0 = 1,
         p5.0 = 1,
         p6.0 = 1,
         p7.0 = 1,
         p8.0 = 1,
         p9.0 = 1,
         p10.0 = 1,
         p11.0 = 1,
         p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p6.1 = (exp(my.par[6,1]*(theta-my.par[6,2]))/(1+exp(my.par[6,1]*(theta-my.par[6,2])))),
         p7.1 = (exp(my.par[7,1]*(theta-my.par[7,2]))/(1+exp(my.par[7,1]*(theta-my.par[7,2])))),
         p8.1 = (exp(my.par[8,1]*(theta-my.par[8,2]))/(1+exp(my.par[8,1]*(theta-my.par[8,2])))),
         p9.1 = (exp(my.par[9,1]*(theta-my.par[9,2]))/(1+exp(my.par[9,1]*(theta-my.par[9,2])))),
         p10.1 = (exp(my.par[10,1]*(theta-my.par[10,2]))/(1+exp(my.par[10,1]*(theta-my.par[10,2])))),
         p11.1 = (exp(my.par[11,1]*(theta-my.par[11,2]))/(1+exp(my.par[11,1]*(theta-my.par[11,2])))),
         p1.2 = 0,
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = 0,
         p5.2 = 0,
         p6.2 = (exp(my.par[6,1]*(theta-my.par[6,3]))/(1+exp(my.par[6,1]*(theta-my.par[6,3])))),
         p7.2 = (exp(my.par[7,1]*(theta-my.par[7,3]))/(1+exp(my.par[7,1]*(theta-my.par[7,3])))),
         p8.2 = (exp(my.par[8,1]*(theta-my.par[8,3]))/(1+exp(my.par[8,1]*(theta-my.par[8,3])))),
         p9.2 = (exp(my.par[9,1]*(theta-my.par[9,3]))/(1+exp(my.par[9,1]*(theta-my.par[9,3])))),
         p10.2 = (exp(my.par[10,1]*(theta-my.par[10,3]))/(1+exp(my.par[10,1]*(theta-my.par[10,3])))),
         p11.2 = (exp(my.par[11,1]*(theta-my.par[11,3]))/(1+exp(my.par[11,1]*(theta-my.par[11,3])))),
         p2.3 = 0,
         p3.3 = 0,
         p6.3 = 0,
         p7.3 = 0,
         p8.3 = 0,
         p9.3 = 0,
         p10.3 = 0,
         p11.3 = 0,
         i1 = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) + 
                                 ((p1.1*(1-p1.1)) - (p1.2*(1-p1.2)))^2/(p1.1-p1.2)),
         i2 = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                 ((p2.1*(1-p2.1)) - (p2.2*(1-p2.2)))^2/(p2.1-p2.2) +
                                 ((p2.2*(1-p2.2)) - (p2.3*(1-p2.3)))^2/(p2.2-p2.3)),
         i3 = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                 ((p3.1*(1-p3.1)) - (p3.2*(1-p3.2)))^2/(p3.1-p3.2) +
                                 ((p3.2*(1-p3.2)) - (p3.3*(1-p3.3)))^2/(p3.2-p3.3)),
         i4 = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                 ((p4.1*(1-p4.1)) - (p4.2*(1-p4.2)))^2/(p4.1-p4.2)),
         i5 = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                 ((p5.1*(1-p5.1)) - (p5.2*(1-p5.2)))^2/(p5.1-p5.2)),
         i6 = my.par[6,1]^2 * (  ((p6.0*(1-p6.0)) - (p6.1*(1-p6.1)))^2/(p6.0-p6.1) +
                                 ((p6.1*(1-p6.1)) - (p6.2*(1-p6.2)))^2/(p6.1-p6.2) +
                                 ((p6.2*(1-p6.2)) - (p6.3*(1-p6.3)))^2/(p6.2-p6.3)),
         i7 = my.par[7,1]^2 * (  ((p7.0*(1-p7.0)) - (p7.1*(1-p7.1)))^2/(p7.0-p7.1) +
                                 ((p7.1*(1-p7.1)) - (p7.2*(1-p7.2)))^2/(p7.1-p7.2) +
                                 ((p7.2*(1-p7.2)) - (p7.3*(1-p7.3)))^2/(p7.2-p7.3)),
         i8 = my.par[8,1]^2 * (  ((p8.0*(1-p8.0)) - (p8.1*(1-p8.1)))^2/(p8.0-p8.1) +
                                 ((p8.1*(1-p8.1)) - (p8.2*(1-p8.2)))^2/(p8.1-p8.2) +
                                 ((p8.2*(1-p8.2)) - (p8.3*(1-p8.3)))^2/(p8.2-p8.3)),
         i9 = my.par[9,1]^2 * (  ((p9.0*(1-p9.0)) - (p9.1*(1-p9.1)))^2/(p9.0-p9.1) +
                                 ((p9.1*(1-p9.1)) - (p9.2*(1-p9.2)))^2/(p9.1-p9.2) +
                                 ((p9.2*(1-p9.2)) - (p9.3*(1-p9.3)))^2/(p9.2-p9.3)),
         i10 = my.par[10,1]^2 * (  ((p10.0*(1-p10.0)) - (p10.1*(1-p10.1)))^2/(p10.0-p10.1) +
                                   ((p10.1*(1-p10.1)) - (p10.2*(1-p10.2)))^2/(p10.1-p10.2) +
                                   ((p10.2*(1-p10.2)) - (p10.3*(1-p10.3)))^2/(p10.2-p10.3)),
         i11 = my.par[11,1]^2 * (  ((p11.0*(1-p11.0)) - (p11.1*(1-p11.1)))^2/(p11.0-p11.1) +
                                   ((p11.1*(1-p11.1)) - (p11.2*(1-p11.2)))^2/(p11.1-p11.2) +
                                   ((p11.2*(1-p11.2)) - (p11.3*(1-p11.3)))^2/(p11.2-p11.3)),
         es1 = p1.1, 
         es2 = p2.1 + p2.2, 
         es3 = p3.1 + p3.2, 
         es4 = p4.1, 
         es5 = p5.1, 
         es6 = p6.1 + p6.2, 
         es7 = p7.1 + p7.2, 
         es8 = p8.1 + p8.2, 
         es9 = p9.1 + p9.2, 
         es10 = p10.1 + p10.2,
         es11 = p11.1 + p11.2,
         i1.sens = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) + 
                                      ((p1.1*(1-p1.1)) - (p1.2*(1-p1.2)))^2/(p1.1-p1.2)),
         i2.sens = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                      ((p2.1*(1-p2.1)) - (p2.3*(1-p2.3)))^2/(p2.1-p2.3)),
         i3.sens = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                      ((p3.1*(1-p3.1)) - (p3.3*(1-p3.3)))^2/(p3.1-p3.3)),
         i4.sens = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                      ((p4.1*(1-p4.1)) - (p4.2*(1-p4.2)))^2/(p4.1-p4.2)),
         i5.sens = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                      ((p5.1*(1-p5.1)) - (p5.2*(1-p5.2)))^2/(p5.1-p5.2)),
         i6.sens = my.par[6,1]^2 * (  ((p6.0*(1-p6.0)) - (p6.1*(1-p6.1)))^2/(p6.0-p6.1) +
                                      ((p6.1*(1-p6.1)) - (p6.3*(1-p6.3)))^2/(p6.1-p6.3)),
         i7.sens = my.par[7,1]^2 * (  ((p7.0*(1-p7.0)) - (p7.1*(1-p7.1)))^2/(p7.0-p7.1) +
                                      ((p7.1*(1-p7.1)) - (p7.3*(1-p7.3)))^2/(p7.1-p7.3)),
         i8.sens = my.par[8,1]^2 * (  ((p8.0*(1-p8.0)) - (p8.1*(1-p8.1)))^2/(p8.0-p8.1) +
                                      ((p8.1*(1-p8.1)) - (p8.3*(1-p8.3)))^2/(p8.1-p8.3)),
         i9.sens = my.par[9,1]^2 * (  ((p9.0*(1-p9.0)) - (p9.1*(1-p9.1)))^2/(p9.0-p9.1) +
                                      ((p9.1*(1-p9.1)) - (p9.3*(1-p9.3)))^2/(p9.1-p9.3)),
         i10.sens = my.par[10,1]^2 * (  ((p10.0*(1-p10.0)) - (p10.1*(1-p10.1)))^2/(p10.0-p10.1) +
                                        ((p10.1*(1-p10.1)) - (p10.3*(1-p10.3)))^2/(p10.1-p10.3)),
         i11.sens = my.par[11,1]^2 * (  ((p11.0*(1-p11.0)) - (p11.1*(1-p11.1)))^2/(p11.0-p11.1) +
                                        ((p11.1*(1-p11.1)) - (p11.3*(1-p11.3)))^2/(p11.1-p11.3)),
         testscore = es1 + es2 + es3 + es4 + es5 + es6 + es7 + es8 + es9 + es10 + es11,
         info = i1 + i2 + i3 + i4 + i5 + i6 + i7 + i8 + i9 + i10 + i11,
         info.sens = i1.sens + i2.sens + i3.sens + i4.sens + i5.sens + i6.sens + 
           i7.sens + i8.sens + i9.sens + i10.sens + i11.sens,
         info.diff = info - info.sens,
         sem = info^(-.5),
         sem.sens = info.sens^(-.5))

```

```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- cam.par.poly[,c("A.cam", "B1.cam", "B2.cam")]
camsf.info.poly <- hoo %>%
  mutate(p1.0 = 1,
         p2.0 = 1,
         p3.0 = 1,
         p4.0 = 1,
         p5.0 = 1,
         p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p1.2 = 0,
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = 0,
         p5.2 = 0,
         p2.3 = 0,
         p3.3 = 0,
         i1 = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) + 
                                 ((p1.1*(1-p1.1)) - (p1.2*(1-p1.2)))^2/(p1.1-p1.2)),
         i2 = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                 ((p2.1*(1-p2.1)) - (p2.2*(1-p2.2)))^2/(p2.1-p2.2) +
                                 ((p2.2*(1-p2.2)) - (p2.3*(1-p2.3)))^2/(p2.2-p2.3)),
         i3 = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                 ((p3.1*(1-p3.1)) - (p3.2*(1-p3.2)))^2/(p3.1-p3.2) +
                                 ((p3.2*(1-p3.2)) - (p3.3*(1-p3.3)))^2/(p3.2-p3.3)),
         i4 = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                 ((p4.1*(1-p4.1)) - (p4.2*(1-p4.2)))^2/(p4.1-p4.2)),
         i5 = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                 ((p5.1*(1-p5.1)) - (p5.2*(1-p5.2)))^2/(p5.1-p5.2)),
         es1 = p1.1, 
         es2 = p2.1 + p2.2, 
         es3 = p3.1 + p3.2, 
         es4 = p4.1, 
         es5 = p5.1,
         i1.sens = my.par[1,1]^2 * (  ((p1.0*(1-p1.0)) - (p1.1*(1-p1.1)))^2/(p1.0-p1.1) + 
                                      ((p1.1*(1-p1.1)) - (p1.2*(1-p1.2)))^2/(p1.1-p1.2)),
         i2.sens = my.par[2,1]^2 * (  ((p2.0*(1-p2.0)) - (p2.1*(1-p2.1)))^2/(p2.0-p2.1) +
                                      ((p2.1*(1-p2.1)) - (p2.3*(1-p2.3)))^2/(p2.1-p2.3)),
         i3.sens = my.par[3,1]^2 * (  ((p3.0*(1-p3.0)) - (p3.1*(1-p3.1)))^2/(p3.0-p3.1) +
                                      ((p3.1*(1-p3.1)) - (p3.3*(1-p3.3)))^2/(p3.1-p3.3)),
         i4.sens = my.par[4,1]^2 * (  ((p4.0*(1-p4.0)) - (p4.1*(1-p4.1)))^2/(p4.0-p4.1) +
                                      ((p4.1*(1-p4.1)) - (p4.2*(1-p4.2)))^2/(p4.1-p4.2)),
         i5.sens = my.par[5,1]^2 * (  ((p5.0*(1-p5.0)) - (p5.1*(1-p5.1)))^2/(p5.0-p5.1) +
                                      ((p5.1*(1-p5.1)) - (p5.2*(1-p5.2)))^2/(p5.1-p5.2)),
         testscore = es1 + es2 + es3 + es4 + es5,
         info = i1 + i2 + i3 + i4 + i5,
         info.sens = i1.sens + i2.sens + i3.sens + i4.sens + i5.sens,
         info.diff = info - info.sens,
         sem = info^(-.5),
         sem.sens = info.sens^(-.5))

```
## Plots for the polytomous model

```{r}

testscore <- drs.info.poly %>%
  select(theta, testscore) %>%
  rename(drsscore = testscore) %>%
  left_join(mdas.info.poly %>% 
              select(theta, testscore) %>%
              rename(mdasscore = testscore), by="theta") %>%
  left_join(camlf.info.poly %>%
              select(theta, testscore) %>%
              rename(camlfscore = testscore), by="theta") %>%
  left_join(camsf.info.poly %>%
              select(theta, testscore) %>%
              rename(camsfscore = testscore), by="theta") %>%
  gather(test, score, 2:5)


plot_test_characteristic_curve <- ggplot(testscore, aes(theta, score, group=test, color=test)) +
  geom_line() +
  scale_color_brewer(palette = "Dark2", 
                     name = "Delirium Instrument",
                     breaks = c("drsscore", "mdasscore", "camlfscore", "camsfscore"),
                     labels = c("DRS-R-98", "MDAS", "CAM-S LF", "CAM-S SF")) + 
  scale_y_continuous("Expected Total Score", breaks=seq(0,40,2)) +
  scale_x_continuous("Delirium Intensity", breaks=seq(-4,8,1))  +
  theme_doug()  

plot_test_characteristic_curve +
  ggtitle("Test Characteristic Curves (Polytomous CFA)")

```



```{r}

testinfo <- drs.info.poly %>%
  select(theta, info) %>%
  rename(drsinfo = info) %>%
  left_join(mdas.info.poly %>% 
              select(theta, info) %>%
              rename(mdasinfo = info), by="theta") %>%
  left_join(camlf.info.poly %>%
              select(theta, info) %>%
              rename(camlfinfo = info), by="theta") %>%
  left_join(camsf.info.poly %>%
              select(theta, info) %>%
              rename(camsfinfo = info), by="theta") %>%
  gather(test, info, 2:5)


plot_test_information <- ggplot(testinfo, aes(theta, info, group=test, color=test)) +
  geom_line() +
  scale_color_brewer(palette = "Dark2", 
                     name = "Delirium Instrument",
                     breaks = c("drsinfo", "mdasinfo", "camlfinfo", "camsfinfo"),
                     labels = c("DRS-R-98", "MDAS", "CAM-S LF", "CAM-S SF")) + 
  scale_y_continuous("Information", breaks=seq(0,12,2)) +
  scale_x_continuous("Delirium Intensity", breaks=seq(-4,8,1))  +
  theme_doug() 

plot_test_information +
  ggtitle("Test Information Curves (Polytomous CFA)")
```

```{r}

testrel <- drs.info.poly %>%
  select(theta, info) %>%
  rename(drsinfo = info) %>%
  left_join(mdas.info.poly %>% 
              select(theta, info) %>%
              rename(mdasinfo = info), by="theta") %>%
  left_join(camlf.info.poly %>%
              select(theta, info) %>%
              rename(camlfinfo = info), by="theta") %>%
  left_join(camsf.info.poly %>%
              select(theta, info) %>%
              rename(camsfinfo = info), by="theta") %>%
  gather(test, info, 2:5) %>%
  mutate(rel = 1 - (1/info)) %>%
  select(-info)


plot_test_reliability <- testrel %>%
  filter(rel>=0) %>%
  ggplot(aes(theta, rel, group=test, color=test)) +
  geom_line() +
  scale_color_brewer(palette = "Dark2", 
                     name = "Delirium Instrument",
                     breaks = c("drsinfo", "mdasinfo", "camlfinfo", "camsfinfo"),
                     labels = c("DRS-R-98", "MDAS", "CAM-S LF", "CAM-S SF")) + 
  scale_y_continuous("Reliability", breaks=seq(0,1,.2), limits = c(0, 1)) +
  scale_x_continuous("Delirium Intensity", breaks=seq(-4,8,1), limits=c(-4, 8))  +
  theme_doug() 

plot_test_reliability +
  ggtitle("Test Reliability Curves (Polytomous CFA)")



```



