

### Alternative Item-Person Maps
This is an alternative of the Item-Person map for the DRS.
```{r, eval=FALSE}

plot2 <- drs.par %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  mutate(f.itemnum = factor(itemnum),
         f.itemnum = factor(f.itemnum, levels = rev(levels(f.itemnum)))) %>%
  ggplot(aes(x = est, y = f.itemnum, group=itemnum)) +
    geom_point() +
    geom_line() +
    scale_y_discrete(labels = c("1" = "DRS 1", 
                                "2" = "DRS 2", 
                                "3" = "DRS 3", 
                                "4" = "DRS 4", 
                                "5" = "DRS 5", 
                                "6" = "DRS 6", 
                                "7" = "DRS 7", 
                                "8" = "DRS 8", 
                                "9" = "DRS 9", 
                                "10" = "DRS 10", 
                                "11" = "DRS 11", 
                                "12" = "DRS 12", 
                                "13" = "DRS 13"),
                     "Item") +
    scale_x_continuous("Delirium Intensity", limits = c(-4, 6))


```


```{r, eval=FALSE}
fscores.drs <- getSavedata_Data(here("mplus_output", "cfa-drs-3.out")) %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(f.drs = f)

# fscores.mdas <- getSavedata_Data(here("mplus_output", "cfa-mdas-3.out")) %>%
#   setNames(tolower(names(.))) %>%
#   select(recordid, f) %>%
#   rename(f.mdas = f)
# 
# fscores.cam <- getSavedata_Data(here("mplus_output", "cfa-cam-3.out")) %>%
#   setNames(tolower(names(.))) %>%
#   select(recordid, f) %>%
#   rename(f.cam = f)
# 
# fscores <- fscores.drs %>%
#   left_join(fscores.mdas, by="recordid") %>%
#   left_join(fscores.cam, by="recordid")

plot1 <- fscores.drs %>%
  ggplot(aes(f.drs)) +
    geom_density(adjust=2) + 
  xlab("Delirium Intensity") +
  ylab("Density") +
  scale_x_continuous(limits = c(-4, 6)) +
  ggtitle("Distribution of estimated delirium intensity")


ggmatrix(list(plot1, plot2), 
         nrow = 2, ncol = 1)

```

This Item-Person maps uses all three instruments.
```{r, eval=FALSE}

 
  
foo.drs<-  drs.par %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.drs) %>%
  mutate(gr.order = recode(itemnum, "1=1; 10=2; 12=3; 11=4; 9=7; 6=9; 5=10; 13=11; 2=13; 7=15; 8=16; 3=17; 4=18;"),
         test = "DRS") 

foo.mdas<-  mdas.par %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.mdas) %>%
  mutate(gr.order = recode(itemnum, "10=1; 5=2; 3=4; 4=5; 2=7; 6=8; 1=12; 7=13; 9=14; 8=17;"),
         gr.order = gr.order+.25,
         test = "MDAS",
         itemnum = itemnum+20) 

foo.cam<-  cam.par %>%
  gather(B, est, 4:5) %>%
  arrange(itemnum, B) %>%
  rename(A = A.cam) %>%
  mutate(gr.order = recode(itemnum, "10=1; 2=2; 6=4; 1=6; 5=7; 3=8; 4=12; 7=13; 8=15; 9=16;"),
         gr.order = gr.order+.5,
         test = "CAM",
         itemnum = itemnum+30) 

xmin <- -4
xmax <- 12
pos1 <- -4
pos2 <- 8.1
labsize <- 2
d1.loc <- 10
d2.loc <- 130
d3.loc <- 170
d4.loc <- 180
d5.loc <- 100
d6.loc <- 90
d7.loc <- 150
d8.loc <- 160
d9.loc <- 70
d10.loc <- 20
d11.loc <- 40
d12.loc <- 30
d13.loc <- 110
m1.loc <- 122.5
m2.loc <- 72.5
m3.loc <- 42.5
m4.loc <- 52.5
m5.loc <- 22.5
m6.loc <- 82.5
m7.loc <- 132.5
m8.loc <- 172.5
m9.loc <- 142.5
m10.loc <- 12.5
c1.loc <- 65
c2.loc <- 25
c3.loc <- 85
c4.loc <- 125
c5.loc <- 75
c6.loc <- 45
c7.loc <- 135
c8.loc <- 155
c9.loc <- 165
c10.loc <- 15
sleep.loc <- mean(c(d1.loc, m10.loc, c10.loc))
attention.loc <- mean(c(d10.loc, m5.loc, c2.loc))
ltmemory.loc <- mean(c(d12.loc))
stmemory.loc <- mean(c(d11.loc, m3.loc, c6.loc))
digitspan.loc <- mean(c(m4.loc))
acute.loc <- mean(c(c1.loc))
orientation.loc <- mean(c(d9.loc, m2.loc, c5.loc))
disthinking.loc <- mean(c(m6.loc, c3.loc))
thoughpro.loc <- mean(c(d6.loc))
language.loc <- mean(c(d5.loc))
visiospatial.loc <- mean(c(d13.loc))
percdis.loc <- mean(c(d2.loc, m7.loc, c7.loc))
psyaggret.loc <- mean(c(m9.loc))
psyagg.loc <- mean(c(d7.loc, c8.loc))
psyret.loc <- mean(c(d8.loc, c9.loc))
delusion.loc <- mean(c(d3.loc, m8.loc))
labaffect.loc <- mean(c(d4.loc))
awareness.loc <- mean(c(m1.loc, c4.loc))



plot2 <-  foo.drs %>%
  bind_rows(foo.mdas) %>%
  bind_rows(foo.cam) %>%
  mutate(gr.order = gr.order*10) %>%
  ggplot(aes(x = est, y = gr.order, group=itemnum, color = test)) +
    geom_point(show.legend = FALSE) +
    geom_line(show.legend = FALSE) +
    scale_color_brewer(palette = "Dark2", 
                     name = "Delirium Instrument",
                     breaks = c("DRS", "MDAS", "CAM"),
                     labels = c("DRS", "MDAS", "CAM-S")) +
    scale_x_continuous("Delirium Intensity", limits = c(xmin, xmax), 
                       breaks = seq(-2, 8, by=2)) +
    scale_y_continuous(name=NULL, trans = "reverse") +
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_line(linetype = "dashed", color = "grey80"),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 17, ymax = 27, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 37, ymax = 47, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 57, ymax = 67, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 77, ymax = 87, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 97, ymax = 107, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 117, ymax = 127, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 137, ymax = 147, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 157, ymax = 167, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 177, ymax = 187, alpha = .2) +
    annotate("text", x = pos1, y = 5, hjust=0, label = "Item", 
             size = labsize, fontface =2) +
    annotate("text", x = pos2, y = 5, hjust=0, label = "Feature domain", 
             size = labsize, fontface =2) +
    annotate("text", x = pos1, y = d1.loc,  hjust=0, label = "DRS 1", 
             size = labsize) +
    annotate("text", x = pos1, y = d2.loc,  hjust=0, label = "DRS 2", 
             size = labsize) +
    annotate("text", x = pos1, y = d3.loc,  hjust=0, label = "DRS 3", 
             size = labsize) +
    annotate("text", x = pos1, y = d4.loc,  hjust=0, label = "DRS 4", 
             size = labsize) +
    annotate("text", x = pos1, y = d5.loc,  hjust=0, label = "DRS 5", 
             size = labsize) +
    annotate("text", x = pos1, y = d6.loc,  hjust=0, label = "DRS 6", 
             size = labsize) +
    annotate("text", x = pos1, y = d7.loc,  hjust=0, label = "DRS 7", 
             size = labsize) +
    annotate("text", x = pos1, y = d8.loc,  hjust=0, label = "DRS 8", 
             size = labsize) +
    annotate("text", x = pos1, y = d9.loc,  hjust=0, label = "DRS 9", 
             size = labsize) +
    annotate("text", x = pos1, y = d10.loc, hjust=0, label = "DRS 10", 
             size = labsize) +
    annotate("text", x = pos1, y = d11.loc, hjust=0, label = "DRS 11", 
             size = labsize) +
    annotate("text", x = pos1, y = d12.loc, hjust=0, label = "DRS 12", 
             size = labsize) +
    annotate("text", x = pos1, y = d13.loc, hjust=0, label = "DRS 13", 
             size = labsize) +
    annotate("text", x = pos1, y = m1.loc,  hjust=0, label = "MDAS 1", 
             size = labsize) +
    annotate("text", x = pos1, y = m2.loc,  hjust=0, label = "MDAS 2", 
             size = labsize) +
    annotate("text", x = pos1, y = m3.loc,  hjust=0, label = "MDAS 3", 
             size = labsize) +
    annotate("text", x = pos1, y = m4.loc,  hjust=0, label = "MDAS 4", 
             size = labsize) +
    annotate("text", x = pos1, y = m5.loc,  hjust=0, label = "MDAS 5", 
             size = labsize) +
    annotate("text", x = pos1, y = m6.loc,  hjust=0, label = "MDAS 6", 
             size = labsize) +
    annotate("text", x = pos1, y = m7.loc,  hjust=0, label = "MDAS 7", 
             size = labsize) +
    annotate("text", x = pos1, y = m8.loc,  hjust=0, label = "MDAS 8", 
             size = labsize) +
    annotate("text", x = pos1, y = m9.loc,  hjust=0, label = "MDAS 9", 
             size = labsize) +
    annotate("text", x = pos1, y = m10.loc, hjust=0, label = "MDAS 10", 
             size = labsize) +
    annotate("text", x = pos1, y = c1.loc, hjust=0, label = "CAM 1", 
             size = labsize) +
    annotate("text", x = pos1, y = c2.loc, hjust=0, label = "CAM 2", 
             size = labsize) +
    annotate("text", x = pos1, y = c3.loc, hjust=0, label = "CAM 3", 
             size = labsize) +
    annotate("text", x = pos1, y = c4.loc, hjust=0, label = "CAM 4", 
             size = labsize) +
    annotate("text", x = pos1, y = c5.loc, hjust=0, label = "CAM 5", 
             size = labsize) +
    annotate("text", x = pos1, y = c6.loc, hjust=0, label = "CAM 6", 
             size = labsize) +
    annotate("text", x = pos1, y = c7.loc, hjust=0, label = "CAM 7", 
             size = labsize) +
    annotate("text", x = pos1, y = c8.loc, hjust=0, label = "CAM 8a", 
             size = labsize) +
    annotate("text", x = pos1, y = c9.loc, hjust=0, label = "CAM 8d", 
             size = labsize) +
    annotate("text", x = pos1, y = c10.loc, hjust=0, label = "CAM 9", 
             size = labsize) +
    annotate("text", x = pos2, y = sleep.loc, hjust=0, 
             label = "Sleep disturbance", size = labsize) +
    annotate("text", x = pos2, y = percdis.loc,  hjust=0, 
             label = "Perceptual disturbance", size = labsize) +
    annotate("text", x = pos2, y = delusion.loc, hjust=0, 
             label = "Delusions", size = labsize) +
    annotate("text", x = pos2, y = labaffect.loc, hjust=0, 
             label = "Labile affect", size = labsize) +
    annotate("text", x = pos2, y = language.loc,  hjust=0, 
             label = "Language impairment", size = labsize) +
    annotate("text", x = pos2, y = thoughpro.loc, hjust=0, 
             label = "Thought process abnormality", size = labsize) +
    annotate("text", x = pos2, y = psyagg.loc, hjust=0, 
             label = "Psychomotor agitation", size = labsize) +
    annotate("text", x = pos2, y = psyret.loc, hjust=0, 
             label = "Psychomotor retardation", size = labsize) +
    annotate("text", x = pos2, y = orientation.loc,  hjust=0, 
             label = "Disorientation", size = labsize) +
    annotate("text", x = pos2, y = attention.loc,  hjust=0, 
             label = "Inattention", size = labsize) +
    annotate("text", x = pos2, y = stmemory.loc,  hjust=0, 
             label = "Short-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = ltmemory.loc,  hjust=0, 
             label = "Long-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = visiospatial.loc,  hjust=0, 
             label = "Visiospatial impairment", size = labsize) +
    annotate("text", x = pos2, y = psyaggret.loc, hjust=0, 
             label = "Psychomotor agitation or retardation", size = labsize) +
    annotate("text", x = pos2, y = digitspan.loc, hjust=0, 
             label = "Impaired Digit Span", size=labsize) +
    annotate("text", x = pos2, y = awareness.loc, hjust=0, 
             label = "Abnormal level of consciousness", size = labsize) +
    annotate("text", x = pos2, y = disthinking.loc, hjust=0, 
             label = "Disorganized thinking", size = labsize) +
    annotate("text", x = pos2, y = acute.loc, hjust=0, 
             label = "Acute change", size = labsize) 
  
plot2
ggsave(here("Figures", "plot2.pdf"), height = 20, units="cm")


```


```{r, eval=FALSE}
fscores.drs <- getSavedata_Data(here("mplus_output", "cfa-drs-3.out")) %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(f.drs = f)

fscores.mdas <- getSavedata_Data(here("mplus_output", "cfa-mdas-3.out")) %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(f.mdas = f)

fscores.cam <- getSavedata_Data(here("mplus_output", "cfa-cam-3.out")) %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(f.cam = f)

fscores <- fscores.drs %>%
  left_join(fscores.mdas, by="recordid") %>%
  left_join(fscores.cam, by="recordid")

plot1 <- fscores %>%
  gather(test, fscore, 2:4) %>%
  ggplot(aes(fscore, group=test, color=test)) +
    geom_density(adjust=2) + 
    geom_rug(alpha = .25, size=.5) +
    xlab("Delirium Intensity") +
    ylab("Density") +
    scale_x_continuous(limits = c(-4, 10), breaks = seq(-4, 8, by = 2)) +
    scale_color_brewer(palette = "Dark2", 
                      name = "Delirium Instrument",
                      breaks = c("f.drs", "f.mdas", "f.cam"),
                      labels = c("DRS", "MDAS", "CAM-S")) + 
    ggtitle("Distribution of estimated delirium intensity") + 
    theme(panel.background = element_blank())


ggmatrix(list(plot1, plot2), 
         nrow = 2, ncol = 1,
          yProportions = c(.2, .8))

ggsave(here("Figures", "plot2a.pdf"), height = 25, units="cm")

```
