

```{r}
# library(plyr)
library(dplyr)
library(tidyr)
library(knitr)
library(stringr)
library(car)
library(MplusAutomation)
library(haven)
library(SNSequate)
library(ggplot2)
library(RColorBrewer)
library(GGally)
library(kableExtra)
library(purrr)
# library(corrr)
```
```{r}
source("ggplot-theme.r")
```

```{r}

maketable <- function(p, d) {
  foo <- basil.pattern %>%
    filter(pattern==p) %>%
    gather(response, label, R0:R18) %>%
    filter(!is.na(label)) %>%
    mutate(y = as.numeric(str_sub(response, start=2)))

  basil.items <- basil.lookup %>%
                    filter(instrument ==d & pattern==p)

  goo <- basil %>%
    select(one_of(as.character(basil.items$item))) %>%
    gather(item, y) %>%
    arrange(item) %>%
    left_join(foo, by = "y") %>%
    mutate(label = ifelse(!is.na(label), label, y),
           label = ifelse(is.na(label), "Missing", label),
           foo = TRUE,
           id = row_number()) %>%
    spread(label, foo) %>%
    select(-id, -y, -pattern, -response) %>%
    group_by(item) %>%
    summarize_all(funs(100*sum(., na.rm=TRUE)/n()))

  basil.items %>%
    select(item, short.label) %>%
    rename('Question' =  short.label) %>%
    left_join(goo, by = "item") %>%
    kable(digits = 0) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                  full_width = F, position = "left")

}


itemtable <- function(d) {
  pattern <- (basil.lookup %>%
                filter(instrument ==d) %>%
                select(-verbatim.q.text) %>%
                distinct(pattern))[[1]]

  for (i in pattern) {
    print(maketable(p=i, d=d))
  }

}

item.parameter.table <- function(filename, nitems) {
  param <- readModels(filename, quiet = TRUE)$parameters$unstandardized
  mc.param <- param %>%
    filter(paramHeader=="F.BY" | 
           paramHeader=="Thresholds") %>%
    mutate(est = as.numeric(est),
           item = ifelse(paramHeader=="Thresholds", 
                        str_split_fixed(param, "\\$1", 2), param),
           parameter = ifelse(paramHeader=="Thresholds", "T", "FL")) %>%
    select(parameter, item, est) %>%
    mutate_all(funs(tolower))
  mc.param <- mc.param[1:(2*nitems),1:3]
  mc.param$est <- as.numeric(mc.param$est)
  mc.param %>%
    spread(parameter, est) %>%
    arrange(desc(fl)) %>%
    kable(col.names = c("Item", "Slope", "Threshold"), 
          digits=c(0, 2, 2)) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                  full_width = F, position = "left")
}

```


```{r}
item.parameter.df.poly <- function(filename, maxThresh, instrument.name) {
  param <- readModels(filename, quiet = TRUE)$parameters$unstandardized
  
  mc.param <- param %>%
    filter(paramHeader=="F.BY" | 
           paramHeader=="Thresholds") %>%
    separate(param, c("item", "cat"), "\\$", fill="right", 
           remove=FALSE, convert=TRUE) %>%
    mutate(parameter = ifelse(paramHeader=="F.BY", "FL", paste0("T", cat))) %>%
    select(parameter, item, est) %>%
    mutate_all(funs(tolower))
  
  mc.param$est <- as.numeric(mc.param$est)

  mc.param <- mc.param %>%
    spread(parameter, est) 
  
  mc.param[[paste0("A.", instrument.name)]] <- mc.param$fl
  for(i in 1:maxThresh) {
    mc.param[[paste0("B",i, ".", instrument.name)]] <- mc.param[[paste0("t",i)]]/mc.param[["fl"]]
  }
  mc.param <- mc.param %>%
    mutate(itemnum = row_number())
  
  mc.param %>%
    select(item, itemnum, starts_with("A"), starts_with("B"))
 
}

item.parameter.table.poly <- function(df, maxThresh, instrument.name) {
  if(maxThresh>1) {
    outcome.type <- "polytomous"
  } 
  else {
    outcome.type <- "dichotomous"
  }
  df %>%
    select(item, starts_with("A"), starts_with("B")) %>%
    kable(digits = 2, 
          col.names = c("Item", "A", paste0("B", 1:maxThresh)),
          caption = paste("Item parameters for", instrument.name, "with", outcome.type, "outcomes")) %>% 
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = F, position = "left")
}

```

```{r}
# Calculate McDonald's omega statistic
myomega <- function(filename) {
  param <- readModels(filename, quiet = TRUE)$parameters$stdyx.standardized
  mc.param <- param %>%
    filter(paramHeader=="F.BY") %>%
    select(param, est) %>%
    mutate(uniqueness = 1-est^2)

  a <- sum(mc.param$est)
  b <- sum(mc.param$uniqueness)

  a^2 / (a^2 + b)
}

```



