
## Model Fitting (Polytomous model)
```{r}
basil3 <- basil %>%
  mutate(rdrs01 = recode(rdrs01, "1=1; 2=2; 3=3; "),
         rdrs02 = recode(rdrs02, "1=1; 2=2; 3=3; "),
         rdrs03 = recode(rdrs03, "1=1; 2=2; 3=3; "),
         rdrs04 = recode(rdrs04, "1=1; 2=2; 3=2; "),
         rdrs05 = recode(rdrs05, "1=1; 2=2; 3=3; "),
         rdrs06 = recode(rdrs06, "1=1; 2=2; 3=3; "),
         rdrs07 = recode(rdrs07, "1=1; 2=2; 3=2; "),
         rdrs08 = recode(rdrs08, "1=1; 2=2; 3=2; "),
         rdrs09 = recode(rdrs09, "1=1; 2=2; 3=3; "),
         rdrs10 = recode(rdrs10, "1=1; 2=2; 3=3; "),
         rdrs11 = recode(rdrs11, "1=1; 2=2; 3=3; "),
         rdrs12 = recode(rdrs12, "1=1; 2=2; 3=3; "),
         rdrs13 = recode(rdrs13, "1=1; 2=2; 3=3; "),
         rmdas01 = recode(rmdas01, "1=1; 2=2; 3=2; "),
         rmdas02 = recode(rmdas02, "1=1; 2=2; 3=3; "),
         rmdas03 = recode(rmdas03, "1=1; 2=2; 3=3; "),
         rmdas04 = recode(rmdas04, "1=1; 2=2; 3=3; "),
         rmdas05 = recode(rmdas05, "1=1; 2=2; 3=3; "),
         rmdas06 = recode(rmdas06, "1=1; 2=2; 3=3; "),
         rmdas07 = recode(rmdas07, "1=1; 2=2; 3=3; "),
         rmdas08 = recode(rmdas08, "1=1; 2=2; 3=3; "),
         rmdas09 = recode(rmdas09, "1=1; 2=2; 3=2; "),
         rmdas10 = recode(rmdas10, "1=1; 2=2; 3=3; "),
         rcamlf1a = recode(rcamlf1a, "1=1; 2=1; "),
         rcamlf2a = recode(rcamlf2a, "1=1; 2=2; "),
         rcamlf3a = recode(rcamlf3a, "1=1; 2=2; "),
         rcamlf4a = recode(rcamlf4a, "1=1; 2=2; "),
         rcamlf5a = recode(rcamlf5a, "1=1; 2=2; "),
         rcamlf6a = recode(rcamlf6a, "1=1; 2=2; "),
         rcamlf7a = recode(rcamlf7a, "1=1; 2=2; "),
         rcamlf8a = recode(rcamlf8a, "1=1; 2=2; "),
         rcamlf8d = recode(rcamlf8d, "1=1; 2=2; "),
         rcamlf9a = recode(rcamlf9a, "1=1; 2=2; "))

```

```{r , eval=FALSE}
basil3 %>%
  select(starts_with("rdrs")) %>%
  gather(item, y)   %>%
  arrange(item) %>%
  mutate(foo = TRUE,
         id = row_number())   %>%
  spread(y, foo)  %>%
  select(-id)   %>%
  group_by(item) %>%
  summarize_all(funs(100*sum(., na.rm=TRUE)/n())) %>%
  select(-`<NA>`) %>%
  arrange(desc(`0`)) %>%
  kable(digits = 2, 
        col.names = c("Item", "0", "1", "2", "3"))


```


```{r, eval=FALSE}
basil3 %>%
  select(starts_with("rmdas")) %>%
  gather(item, y)   %>%
  arrange(item) %>%
  mutate(foo = TRUE,
         id = row_number())   %>%
  spread(y, foo)  %>%
  select(-id)   %>%
  group_by(item) %>%
  summarize_all(funs(100*sum(., na.rm=TRUE)/n()))  %>%
  select(-`<NA>`) %>%
  arrange(desc(`0`)) %>%
  kable(digits = 2, 
        col.names = c("Item", "0", "1", "2", "3"))
```


```{r, eval=FALSE}
basil3 %>%
  select(starts_with("rcam")) %>%
  gather(item, y)   %>%
  arrange(item) %>%
  mutate(foo = TRUE,
         id = row_number())   %>%
  spread(y, foo)  %>%
  select(-id)   %>%
  group_by(item) %>%
  summarize_all(funs(100*sum(., na.rm=TRUE)/n())) %>%
  select(-`<NA>`) %>%
  arrange(desc(`0`)) %>%
  kable(digits = 2, 
        col.names = c("Item", "0", "1", "2"))
```

### DRS CFA model with polytomous outcome
```{r}
### 2PL model

param <- readModels("cfa-drs-2.out")$parameters$unstandardized
mc.param <- param %>%
  filter(paramHeader=="F.BY" | 
         paramHeader=="Thresholds" |
         (paramHeader=="Variances" & param=="F")) %>%
  mutate(est = as.numeric(est)) %>%
  mutate_all(funs(tolower))
  
mc.param <- mc.param[1:27,1:3]
# The sleep item was previously categorized 0, 1 vs 2, 3.  
# Changing it to a four category outcome, means fixing the 2nd threshold 
mc.param$param[mc.param$param=="rdrs01$1"] <- "rdrs01$2"

myParam <- data.frame(f1s = 0)
for (i in 1:dim(mc.param)[1]) {
  if (mc.param$paramHeader[i]=="f.by") {
    myParam[[paste0("f",i, "s")]] = paste0(gsub("\\.", " ", 
                                                mc.param$paramHeader[i]), " ",
                                          mc.param$param[i], 
                                          "@", mc.param$est[i])
  }
  if (mc.param$paramHeader[i]=="thresholds") {
    myParam[[paste0("f",i, "s")]] = paste0("[", mc.param$param[i], 
                                           "@", mc.param$est[i],"]")
  }
  if (mc.param$paramHeader[i]=="variances") {
    myParam[[paste0("f",i, "s")]] = paste0(mc.param$param[i], 
                                           "*")
  }
}

goo <- paste(paste0("[[f", 1:dim(mc.param)[1], "s]];"), collapse = " \n ")
model.drs.3 <- loopReplace(goo, myParam)
model.drs.3 <- paste(model.drs.3, "\n", "[rdrs06$2*5];")

cfa.drs.3.body <- mplusObject(
  ANALYSIS = "estimator = mlr; link=logit; type=complex;",
  VARIABLE = "cluster = recordid; CATEGORICAL ARE all;",
  MODEL = model.drs.3,
  OUTPUT = "",
  SAVEDATA = "save = fscores; file = fscores-drs-poly.dat;",
  usevariables = c("recordid", "rdrs01", "rdrs02", "rdrs07", "rdrs08", 
                   "rdrs09", "rdrs10", "rdrs11", "rdrs03", 
                   "rdrs04", "rdrs05", "rdrs06", "rdrs12", "rdrs13"),
  rdata = basil3)
cfa.drs.3.fit <- mplusModeler(cfa.drs.3.body, 
                               modelout = "cfa-drs-3.inp", run = TRUE)

```
```{r}
drs.par.poly <- readModels("cfa-drs-3.out")$parameters$unstandardized

drs.par.poly <- drs.par.poly %>%
      filter(paramHeader=="F.BY" | 
           paramHeader=="Thresholds") %>%
  separate(param, c("item", "cat"), "\\$", fill="right", 
           remove=FALSE, convert=TRUE) %>%
  mutate(parameter = ifelse(paramHeader=="F.BY", "FL", paste0("T", cat))) %>%
    select(parameter, item, est) %>%
    mutate_all(funs(tolower))

drs.par.poly$est <- as.numeric(drs.par.poly$est)
  
drs.par.poly <- drs.par.poly %>% 
  spread(parameter, est) %>%
  mutate(B1.drs = t1/fl,
         B2.drs = t2/fl,
         B3.drs = t3/fl,
         A.drs = fl,
         itemnum = row_number()) %>%
  select(item, itemnum, A.drs, B1.drs, B2.drs, B3.drs)


drs.par.poly %>%
  select(-itemnum) %>%
  kable(digits = 2, col.names = c("Item", "A", "B1", "B2", "B3")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = F, position = "center")



```


### MDAS CFA model with polytomous outcome
```{r}
### 2PL model

param <- readModels("cfa-mdas-2.out")$parameters$unstandardized
mc.param <- param %>%
  filter(paramHeader=="F.BY" | 
         paramHeader=="Thresholds" |
         (paramHeader=="Variances" & param=="F")) %>%
  mutate(est = as.numeric(est)) %>%
  mutate_all(funs(tolower))
  
mc.param <- mc.param[1:21,1:3]
# The sleep item was previously categorized 0, 1 vs 2, 3.  
# Changing it to a four category outcome, means fixing the 2nd threshold 
mc.param$param[mc.param$param=="rmdas10$1"] <- "rmdas10$2"

myParam <- data.frame(f1s = 0)
for (i in 1:dim(mc.param)[1]) {
  if (mc.param$paramHeader[i]=="f.by") {
    myParam[[paste0("f",i, "s")]] = paste0(gsub("\\.", " ", 
                                                mc.param$paramHeader[i]), " ",
                                          mc.param$param[i], 
                                          "@", mc.param$est[i])
  }
  if (mc.param$paramHeader[i]=="thresholds") {
    myParam[[paste0("f",i, "s")]] = paste0("[", mc.param$param[i], 
                                           "@", mc.param$est[i],"]")
  }
  if (mc.param$paramHeader[i]=="variances") {
    myParam[[paste0("f",i, "s")]] = paste0(mc.param$param[i], 
                                           "*")
  }
}

goo <- paste(paste0("[[f", 1:dim(mc.param)[1], "s]];"), collapse = " \n ")
model.mdas.3 <- loopReplace(goo, myParam)
model.mdas.3 <- paste(model.mdas.3, "\n", "[rmdas06$2*5];")
model.mdas.3 <- paste(model.mdas.3, "\n", "[rmdas01$2*5];")
model.mdas.3 <- paste(model.mdas.3, "\n", "[rmdas06$3*6];")

cfa.mdas.3.body <- mplusObject(
  ANALYSIS = "estimator = mlr; link=logit; type=complex;",
  VARIABLE = "cluster = recordid; CATEGORICAL ARE all;",
  MODEL = model.mdas.3,
  OUTPUT = "",
  SAVEDATA = "save = fscores; file = fscores-mdas-poly.dat;",
  usevariables = c("recordid", "rmdas01", "rmdas02", "rmdas03", 
                   "rmdas04", "rmdas05", "rmdas06", "rmdas07", 
                   "rmdas08", "rmdas09", "rmdas10"),
  rdata = basil3)
cfa.mdas.3.fit <- mplusModeler(cfa.mdas.3.body, 
                               modelout = "cfa-mdas-3.inp", run = TRUE)


```

```{r}
mdas.par.poly <- readModels("cfa-mdas-3.out")$parameters$unstandardized

mdas.par.poly <- mdas.par.poly %>%
      filter(paramHeader=="F.BY" | 
           paramHeader=="Thresholds") %>%
  separate(param, c("item", "cat"), "\\$", fill="right", 
           remove=FALSE, convert=TRUE) %>%
  mutate(parameter = ifelse(paramHeader=="F.BY", "FL", paste0("T", cat))) %>%
    select(parameter, item, est) %>%
    mutate_all(funs(tolower))

mdas.par.poly$est <- as.numeric(mdas.par.poly$est)
  
mdas.par.poly <- mdas.par.poly %>% 
  spread(parameter, est) %>%
  mutate(B1.mdas = t1/fl,
         B2.mdas = t2/fl,
         B3.mdas = t3/fl,
         A.mdas = fl,
         itemnum = row_number()) %>%
  select(item, itemnum, A.mdas, B1.mdas, B2.mdas, B3.mdas)

mdas.par.poly %>%
  select(-itemnum) %>%
  kable(digits = 2, col.names = c("Item", "A", "B1", "B2", "B3")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = F, position = "center")
    
```

### CAM-S CFA model with polytomous outcome
```{r}
### 2PL model

param <- readModels("cfa-cam-2.out")$parameters$unstandardized
mc.param <- param %>%
  filter(paramHeader=="F.BY" | 
         paramHeader=="Thresholds" |
         (paramHeader=="Variances" & param=="F")) %>%
  mutate(est = as.numeric(est)) %>%
  mutate_all(funs(tolower))
  
mc.param <- mc.param[1:21,1:3]
# The sleep item was previously categorized 0, 1 vs 2, 3.  
# Changing it to a four category outcome, means fixing the 2nd threshold 
mc.param$param[mc.param$param=="rcamlf9a$1"] <- "rcamlf9a$2"

myParam <- data.frame(f1s = 0)
for (i in 1:dim(mc.param)[1]) {
  if (mc.param$paramHeader[i]=="f.by") {
    myParam[[paste0("f",i, "s")]] = paste0(gsub("\\.", " ", 
                                                mc.param$paramHeader[i]), " ",
                                          mc.param$param[i], 
                                          "@", mc.param$est[i])
  }
  if (mc.param$paramHeader[i]=="thresholds") {
    myParam[[paste0("f",i, "s")]] = paste0("[", mc.param$param[i], 
                                           "@", mc.param$est[i],"]")
  }
  if (mc.param$paramHeader[i]=="variances") {
    myParam[[paste0("f",i, "s")]] = paste0(mc.param$param[i], 
                                           "*")
  }
}

goo <- paste(paste0("[[f", 1:dim(mc.param)[1], "s]];"), collapse = " \n ")
model.cam.3 <- loopReplace(goo, myParam)
model.cam.3 <- paste(model.cam.3, "\n", "[rcamlf3a$2*5];")
model.cam.3 <- paste(model.cam.3, "\n", "[rcamlf4a$2*5];")


cfa.cam.3.body <- mplusObject(
  ANALYSIS = "estimator = mlr; link=logit; type=complex;",
  VARIABLE = "cluster = recordid; CATEGORICAL ARE all;",
  MODEL = model.cam.3,
  OUTPUT = "",
  SAVEDATA = "save = fscores; file = fscores-cam-poly.dat;",
  usevariables = c("recordid", "rcamlf1a", "rcamlf2a", "rcamlf3a", 
                   "rcamlf4a", "rcamlf5a",
                   "rcamlf6a", "rcamlf7a", "rcamlf8a", "rcamlf8d",   
                   "rcamlf9a"),
  rdata = basil3)
cfa.cam.3.fit <- mplusModeler(cfa.cam.3.body, 
                               modelout = "cfa-cam-3.inp", run = TRUE)


```

```{r}
cam.par.poly <- readModels("cfa-cam-3.out")$parameters$unstandardized

cam.par.poly <- cam.par.poly %>%
      filter(paramHeader=="F.BY" | 
           paramHeader=="Thresholds") %>%
  separate(param, c("item", "cat"), "\\$", fill="right", 
           remove=FALSE, convert=TRUE) %>%
  mutate(parameter = ifelse(paramHeader=="F.BY", "FL", paste0("T", cat))) %>%
    select(parameter, item, est) %>%
    mutate_all(funs(tolower))

cam.par.poly$est <- as.numeric(cam.par.poly$est)
  
cam.par.poly <- cam.par.poly %>% 
  spread(parameter, est) %>%
  mutate(B1.cam = t1/fl,
         B2.cam = t2/fl,
         A.cam = fl,
         itemnum = row_number()) %>%
  select(item, itemnum, A.cam, B1.cam, B2.cam)

cam.par.poly %>%
  select(-itemnum) %>%
  kable(digits = 2, col.names = c("Item", "A", "B1", "B2")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = F, position = "center")
    
```









