



```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- drs.par[,c("A.drs", "B1.drs", "B2.drs", "B3.drs")]
drs.info.poly <- hoo %>%
  mutate(p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p6.1 = (exp(my.par[6,1]*(theta-my.par[6,2]))/(1+exp(my.par[6,1]*(theta-my.par[6,2])))),
         p7.1 = (exp(my.par[7,1]*(theta-my.par[7,2]))/(1+exp(my.par[7,1]*(theta-my.par[7,2])))),
         p8.1 = (exp(my.par[8,1]*(theta-my.par[8,2]))/(1+exp(my.par[8,1]*(theta-my.par[8,2])))),
         p9.1 = (exp(my.par[9,1]*(theta-my.par[9,2]))/(1+exp(my.par[9,1]*(theta-my.par[9,2])))),
         p10.1 = (exp(my.par[10,1]*(theta-my.par[10,2]))/(1+exp(my.par[10,1]*(theta-my.par[10,2])))),
         p11.1 = (exp(my.par[11,1]*(theta-my.par[11,2]))/(1+exp(my.par[11,1]*(theta-my.par[11,2])))),
         p12.1 = (exp(my.par[12,1]*(theta-my.par[12,2]))/(1+exp(my.par[12,1]*(theta-my.par[12,2])))),
         p13.1 = (exp(my.par[13,1]*(theta-my.par[13,2]))/(1+exp(my.par[13,1]*(theta-my.par[13,2])))),
         p1.2 = (exp(my.par[1,1]*(theta-my.par[1,3]))/(1+exp(my.par[1,1]*(theta-my.par[1,3])))),
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = (exp(my.par[4,1]*(theta-my.par[4,3]))/(1+exp(my.par[4,1]*(theta-my.par[4,3])))),
         p5.2 = (exp(my.par[5,1]*(theta-my.par[5,3]))/(1+exp(my.par[5,1]*(theta-my.par[5,3])))),
         p6.2 = (exp(my.par[6,1]*(theta-my.par[6,3]))/(1+exp(my.par[6,1]*(theta-my.par[6,3])))),
         p7.2 = (exp(my.par[7,1]*(theta-my.par[7,3]))/(1+exp(my.par[7,1]*(theta-my.par[7,3])))),
         p8.2 = (exp(my.par[8,1]*(theta-my.par[8,3]))/(1+exp(my.par[8,1]*(theta-my.par[8,3])))),
         p9.2 = (exp(my.par[9,1]*(theta-my.par[9,3]))/(1+exp(my.par[9,1]*(theta-my.par[9,3])))),
         p10.2 = (exp(my.par[10,1]*(theta-my.par[10,3]))/(1+exp(my.par[10,1]*(theta-my.par[10,3])))),
         p11.2 = (exp(my.par[11,1]*(theta-my.par[11,3]))/(1+exp(my.par[11,1]*(theta-my.par[11,3])))),
         p12.2 = (exp(my.par[12,1]*(theta-my.par[12,3]))/(1+exp(my.par[12,1]*(theta-my.par[12,3])))),
         p13.2 = (exp(my.par[13,1]*(theta-my.par[13,3]))/(1+exp(my.par[13,1]*(theta-my.par[13,3])))),
         p1.3 = (exp(my.par[1,1]*(theta-my.par[1,4]))/(1+exp(my.par[1,1]*(theta-my.par[1,4])))),
         p2.3 = (exp(my.par[2,1]*(theta-my.par[2,4]))/(1+exp(my.par[2,1]*(theta-my.par[2,4])))),
         p3.3 = (exp(my.par[3,1]*(theta-my.par[3,4]))/(1+exp(my.par[3,1]*(theta-my.par[3,4])))),
         p5.3 = (exp(my.par[5,1]*(theta-my.par[5,4]))/(1+exp(my.par[5,1]*(theta-my.par[5,4])))),
         p6.3 = (exp(my.par[6,1]*(theta-my.par[6,4]))/(1+exp(my.par[6,1]*(theta-my.par[6,4])))),
         p9.3 = (exp(my.par[9,1]*(theta-my.par[9,4]))/(1+exp(my.par[9,1]*(theta-my.par[9,4])))),
         p10.3 = (exp(my.par[10,1]*(theta-my.par[10,4]))/(1+exp(my.par[10,1]*(theta-my.par[10,4])))),
         p11.3 = (exp(my.par[11,1]*(theta-my.par[11,4]))/(1+exp(my.par[11,1]*(theta-my.par[11,4])))),
         p12.3 = (exp(my.par[12,1]*(theta-my.par[12,4]))/(1+exp(my.par[12,1]*(theta-my.par[12,4])))),
         p13.3 = (exp(my.par[13,1]*(theta-my.par[13,4]))/(1+exp(my.par[13,1]*(theta-my.par[13,4])))),    
         i1 = my.par[1,1]^2 * (  ((1*(1-1)) - (p1.1*(1-p1.1)))^2/(1-p1.1) + ((p1.1*(1-p1.1))-(p1.2*(1-p1.2)))^2/(p1.1-p1.2) + ((p1.2*(1-p1.2))-(p1.3*(1-p1.3)))^2/(p1.2-p1.3) + ((p1.3*(1-p1.3))-(0*(1-0)))^2/(p1.3-0)),
         i2 = my.par[2,1]^2 * (  ((1*(1-1)) - (p2.1*(1-p2.1)))^2/(1-p2.1) + ((p2.1*(1-p2.1))-(p2.2*(1-p2.2)))^2/(p2.1-p2.2) + ((p2.2*(1-p2.2))-(p2.3*(1-p2.3)))^2/(p2.2-p2.3) + ((p2.3*(1-p2.3))-(0*(1-0)))^2/(p2.3-0)),
         i3 = my.par[3,1]^2 * (  ((1*(1-1)) - (p3.1*(1-p3.1)))^2/(1-p3.1) + ((p3.1*(1-p3.1))-(p3.2*(1-p3.2)))^2/(p3.1-p3.2) + ((p3.2*(1-p3.2))-(p3.3*(1-p3.3)))^2/(p3.2-p3.3) + ((p3.3*(1-p3.3))-(0*(1-0)))^2/(p3.3-0)),
         i4 = my.par[4,1]^2 * (  ((1*(1-1)) - (p4.1*(1-p4.1)))^2/(1-p4.1) + ((p4.1*(1-p4.1))-(p4.2*(1-p4.2)))^2/(p4.1-p4.2) + ((p4.2*(1-p4.2))-(0*(1-0)))^2/(p4.2-0)),         
         i5 = my.par[5,1]^2 * (  ((1*(1-1)) - (p5.1*(1-p5.1)))^2/(1-p5.1) + ((p5.1*(1-p5.1))-(p5.2*(1-p5.2)))^2/(p5.1-p5.2) + ((p5.2*(1-p5.2))-(p5.3*(1-p5.3)))^2/(p5.2-p5.3) + ((p5.3*(1-p5.3))-(0*(1-0)))^2/(p5.3-0)),
         i6 = my.par[6,1]^2 * (  ((1*(1-1)) - (p6.1*(1-p6.1)))^2/(1-p6.1) + ((p6.1*(1-p6.1))-(p6.2*(1-p6.2)))^2/(p6.1-p6.2) + ((p6.2*(1-p6.2))-(p6.3*(1-p6.3)))^2/(p6.2-p6.3) + ((p6.3*(1-p6.3))-(0*(1-0)))^2/(p6.3-0)),
         i7 = my.par[7,1]^2 * (  ((1*(1-1)) - (p7.1*(1-p7.1)))^2/(1-p7.1) + ((p7.1*(1-p7.1))-(p7.2*(1-p7.2)))^2/(p7.1-p7.2) + ((p7.2*(1-p7.2))-(0*(1-0)))^2/(p7.2-0)),
         i8 = my.par[8,1]^2 * (  ((1*(1-1)) - (p8.1*(1-p8.1)))^2/(1-p8.1) + ((p8.1*(1-p8.1))-(p8.2*(1-p8.2)))^2/(p8.1-p8.2) + ((p8.2*(1-p8.2))-(0*(1-0)))^2/(p8.2-0)),         
         i9 = my.par[9,1]^2 * (  ((1*(1-1)) - (p9.1*(1-p9.1)))^2/(1-p9.1) + ((p9.1*(1-p9.1))-(p9.2*(1-p9.2)))^2/(p9.1-p9.2) + ((p9.2*(1-p9.2))-(p9.3*(1-p9.3)))^2/(p9.2-p9.3) + ((p9.3*(1-p9.3))-(0*(1-0)))^2/(p9.3-0)),
         i10 = my.par[10,1]^2 * (  ((1*(1-1)) - (p10.1*(1-p10.1)))^2/(1-p10.1) + ((p10.1*(1-p10.1))-(p10.2*(1-p10.2)))^2/(p10.1-p10.2) + ((p10.2*(1-p10.2))-(p10.3*(1-p10.3)))^2/(p10.2-p10.3) + ((p10.3*(1-p10.3))-(0*(1-0)))^2/(p10.3-0)),
         i11 = my.par[11,1]^2 * (  ((1*(1-1)) - (p11.1*(1-p11.1)))^2/(1-p11.1) + ((p11.1*(1-p11.1))-(p11.2*(1-p11.2)))^2/(p11.1-p11.2) + ((p11.2*(1-p11.2))-(p11.3*(1-p11.3)))^2/(p11.2-p11.3) + ((p11.3*(1-p11.3))-(0*(1-0)))^2/(p11.3-0)),
         i12 = my.par[12,1]^2 * (  ((1*(1-1)) - (p12.1*(1-p12.1)))^2/(1-p12.1) + ((p12.1*(1-p12.1))-(p12.2*(1-p12.2)))^2/(p12.1-p12.2) + ((p12.2*(1-p12.2))-(p12.3*(1-p12.3)))^2/(p12.2-p12.3) + ((p12.3*(1-p12.3))-(0*(1-0)))^2/(p12.3-0)),
         i13 = my.par[13,1]^2 * (  ((1*(1-1)) - (p13.1*(1-p13.1)))^2/(1-p13.1) + ((p13.1*(1-p13.1))-(p13.2*(1-p13.2)))^2/(p13.1-p13.2) + ((p13.2*(1-p13.2))-(p13.3*(1-p13.3)))^2/(p13.2-p13.3) + ((p13.3*(1-p13.3))-(0*(1-0)))^2/(p13.3-0)),
         es1 = p1.1 + p1.2 + p1.3, 
         es2 = p2.1 + p2.2 + p2.3, 
         es3 = p3.1 + p3.2 + p3.3, 
         es4 = p4.1 + p4.2, 
         es5 = p5.1 + p5.2 + p5.3, 
         es6 = p6.1 + p6.2 + p6.3, 
         es7 = p7.1 + p7.2, 
         es8 = p8.1 + p8.2, 
         es9 = p9.1 + p9.2 + p9.3, 
         es10 = p10.1 + p10.2 + p10.3, 
         es11 = p11.1 + p11.2 + p11.3, 
         es12 = p12.1 + p12.2 + p12.3, 
         es13 = p13.1 + p13.2 + p13.3, 
         testscore = es1+es2+es3+es4+es5+es6+es7+es8+es9+es10+es11+es12+es13,
         info = i1+i2+i3+i4+i5+i6+i7+i8+i9+i10+i11+i12+i13)

```


```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- mdas.par[,c("A.mdas", "B1.mdas", "B2.mdas", "B3.mdas")]
mdas.info.poly <- hoo %>%
  mutate(p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p6.1 = (exp(my.par[6,1]*(theta-my.par[6,2]))/(1+exp(my.par[6,1]*(theta-my.par[6,2])))),
         p7.1 = (exp(my.par[7,1]*(theta-my.par[7,2]))/(1+exp(my.par[7,1]*(theta-my.par[7,2])))),
         p8.1 = (exp(my.par[8,1]*(theta-my.par[8,2]))/(1+exp(my.par[8,1]*(theta-my.par[8,2])))),
         p9.1 = (exp(my.par[9,1]*(theta-my.par[9,2]))/(1+exp(my.par[9,1]*(theta-my.par[9,2])))),
         p10.1 = (exp(my.par[10,1]*(theta-my.par[10,2]))/(1+exp(my.par[10,1]*(theta-my.par[10,2])))),
         p1.2 = (exp(my.par[1,1]*(theta-my.par[1,3]))/(1+exp(my.par[1,1]*(theta-my.par[1,3])))),
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = (exp(my.par[4,1]*(theta-my.par[4,3]))/(1+exp(my.par[4,1]*(theta-my.par[4,3])))),
         p5.2 = (exp(my.par[5,1]*(theta-my.par[5,3]))/(1+exp(my.par[5,1]*(theta-my.par[5,3])))),
         p6.2 = (exp(my.par[6,1]*(theta-my.par[6,3]))/(1+exp(my.par[6,1]*(theta-my.par[6,3])))),
         p7.2 = (exp(my.par[7,1]*(theta-my.par[7,3]))/(1+exp(my.par[7,1]*(theta-my.par[7,3])))),
         p8.2 = (exp(my.par[8,1]*(theta-my.par[8,3]))/(1+exp(my.par[8,1]*(theta-my.par[8,3])))),
         p9.2 = (exp(my.par[9,1]*(theta-my.par[9,3]))/(1+exp(my.par[9,1]*(theta-my.par[9,3])))),
         p10.2 = (exp(my.par[10,1]*(theta-my.par[10,3]))/(1+exp(my.par[10,1]*(theta-my.par[10,3])))),
         p2.3 = (exp(my.par[2,1]*(theta-my.par[2,4]))/(1+exp(my.par[2,1]*(theta-my.par[2,4])))),
         p3.3 = (exp(my.par[3,1]*(theta-my.par[3,4]))/(1+exp(my.par[3,1]*(theta-my.par[3,4])))),
         p4.3 = (exp(my.par[4,1]*(theta-my.par[4,4]))/(1+exp(my.par[4,1]*(theta-my.par[4,4])))),
         p5.3 = (exp(my.par[5,1]*(theta-my.par[5,4]))/(1+exp(my.par[5,1]*(theta-my.par[5,4])))),
         p6.3 = (exp(my.par[6,1]*(theta-my.par[6,4]))/(1+exp(my.par[6,1]*(theta-my.par[6,4])))),
         p7.3 = (exp(my.par[7,1]*(theta-my.par[7,4]))/(1+exp(my.par[7,1]*(theta-my.par[7,4])))),
         p8.3 = (exp(my.par[8,1]*(theta-my.par[8,4]))/(1+exp(my.par[8,1]*(theta-my.par[8,4])))),
         p10.3 = (exp(my.par[10,1]*(theta-my.par[10,4]))/(1+exp(my.par[10,1]*(theta-my.par[10,4])))),
         i1 = my.par[1,1]^2 * (  ((1*(1-1)) - (p1.1*(1-p1.1)))^2/(1-p1.1) + ((p1.1*(1-p1.1))-(p1.2*(1-p1.2)))^2/(p1.1-p1.2) + ((p1.2*(1-p1.2))-(0*(1-0)))^2/(p1.2-0)),
         i2 = my.par[2,1]^2 * (  ((1*(1-1)) - (p2.1*(1-p2.1)))^2/(1-p2.1) + ((p2.1*(1-p2.1))-(p2.2*(1-p2.2)))^2/(p2.1-p2.2) + ((p2.2*(1-p2.2))-(p2.3*(1-p2.3)))^2/(p2.2-p2.3) + ((p2.3*(1-p2.3))-(0*(1-0)))^2/(p2.3-0)),
         i3 = my.par[3,1]^2 * (  ((1*(1-1)) - (p3.1*(1-p3.1)))^2/(1-p3.1) + ((p3.1*(1-p3.1))-(p3.2*(1-p3.2)))^2/(p3.1-p3.2) + ((p3.2*(1-p3.2))-(p3.3*(1-p3.3)))^2/(p3.2-p3.3) + ((p3.3*(1-p3.3))-(0*(1-0)))^2/(p3.3-0)),
         i4 = my.par[4,1]^2 * (  ((1*(1-1)) - (p4.1*(1-p4.1)))^2/(1-p4.1) + ((p4.1*(1-p4.1))-(p4.2*(1-p4.2)))^2/(p4.1-p4.2) + ((p4.2*(1-p4.2))-(p4.3*(1-p4.3)))^2/(p4.2-p4.3) + ((p4.3*(1-p4.3))-(0*(1-0)))^2/(p4.3-0)),
         i5 = my.par[5,1]^2 * (  ((1*(1-1)) - (p5.1*(1-p5.1)))^2/(1-p5.1) + ((p5.1*(1-p5.1))-(p5.2*(1-p5.2)))^2/(p5.1-p5.2) + ((p5.2*(1-p5.2))-(p5.3*(1-p5.3)))^2/(p5.2-p5.3) + ((p5.3*(1-p5.3))-(0*(1-0)))^2/(p5.3-0)),
         i6 = my.par[6,1]^2 * (  ((1*(1-1)) - (p6.1*(1-p6.1)))^2/(1-p6.1) + ((p6.1*(1-p6.1))-(p6.2*(1-p6.2)))^2/(p6.1-p6.2) + ((p6.2*(1-p6.2))-(p6.3*(1-p6.3)))^2/(p6.2-p6.3) + ((p6.3*(1-p6.3))-(0*(1-0)))^2/(p6.3-0)),
         i7 = my.par[7,1]^2 * (  ((1*(1-1)) - (p7.1*(1-p7.1)))^2/(1-p7.1) + ((p7.1*(1-p7.1))-(p7.2*(1-p7.2)))^2/(p7.1-p7.2) + ((p7.2*(1-p7.2))-(p7.3*(1-p7.3)))^2/(p7.2-p7.3) + ((p7.3*(1-p7.3))-(0*(1-0)))^2/(p7.3-0)),
         i8 = my.par[8,1]^2 * (  ((1*(1-1)) - (p8.1*(1-p8.1)))^2/(1-p8.1) + ((p8.1*(1-p8.1))-(p8.2*(1-p8.2)))^2/(p8.1-p8.2) + ((p8.2*(1-p8.2))-(p8.3*(1-p8.3)))^2/(p8.2-p8.3) + ((p8.3*(1-p8.3))-(0*(1-0)))^2/(p8.3-0)),
         i9 = my.par[9,1]^2 * (  ((1*(1-1)) - (p9.1*(1-p9.1)))^2/(1-p9.1) + ((p9.1*(1-p9.1))-(p9.2*(1-p9.2)))^2/(p9.1-p9.2) + ((p9.2*(1-p9.2))-(0*(1-0)))^2/(p9.2-0)),
         i10 = my.par[10,1]^2 * (  ((1*(1-1)) - (p10.1*(1-p10.1)))^2/(1-p10.1) + ((p10.1*(1-p10.1))-(p10.2*(1-p10.2)))^2/(p10.1-p10.2) + ((p10.2*(1-p10.2))-(p10.3*(1-p10.3)))^2/(p10.2-p10.3) + ((p10.3*(1-p10.3))-(0*(1-0)))^2/(p10.3-0)),
         es1 = p1.1 + p1.2, 
         es2 = p2.1 + p2.2 + p2.3, 
         es3 = p3.1 + p3.2 + p3.3, 
         es4 = p4.1 + p4.2 + p4.3, 
         es5 = p5.1 + p5.2 + p5.3, 
         es6 = p6.1 + p6.2 + p6.3, 
         es7 = p7.1 + p7.2 + p7.3, 
         es8 = p8.1 + p8.2 + p8.3, 
         es9 = p9.1 + p9.2, 
         es10 = p10.1 + p10.2 + p10.3, 
         testscore = es1+es2+es3+es4+es5+es6+es7+es8+es9+es10,
         info = i1+i2+i3+i4+i5+i6+i7+i8+i9+i10)

```


```{r}
theta <- seq(-4, 8, by= .01)
hoo <- data.frame(theta)

my.par <- cam.par[,c("A.cam", "B1.cam", "B2.cam")]
cam.info.poly <- hoo %>%
  mutate(p1.1 = (exp(my.par[1,1]*(theta-my.par[1,2]))/(1+exp(my.par[1,1]*(theta-my.par[1,2])))),
         p2.1 = (exp(my.par[2,1]*(theta-my.par[2,2]))/(1+exp(my.par[2,1]*(theta-my.par[2,2])))),
         p3.1 = (exp(my.par[3,1]*(theta-my.par[3,2]))/(1+exp(my.par[3,1]*(theta-my.par[3,2])))),
         p4.1 = (exp(my.par[4,1]*(theta-my.par[4,2]))/(1+exp(my.par[4,1]*(theta-my.par[4,2])))),
         p5.1 = (exp(my.par[5,1]*(theta-my.par[5,2]))/(1+exp(my.par[5,1]*(theta-my.par[5,2])))),
         p6.1 = (exp(my.par[6,1]*(theta-my.par[6,2]))/(1+exp(my.par[6,1]*(theta-my.par[6,2])))),
         p7.1 = (exp(my.par[7,1]*(theta-my.par[7,2]))/(1+exp(my.par[7,1]*(theta-my.par[7,2])))),
         p8.1 = (exp(my.par[8,1]*(theta-my.par[8,2]))/(1+exp(my.par[8,1]*(theta-my.par[8,2])))),
         p9.1 = (exp(my.par[9,1]*(theta-my.par[9,2]))/(1+exp(my.par[9,1]*(theta-my.par[9,2])))),
         p10.1 = (exp(my.par[10,1]*(theta-my.par[10,2]))/(1+exp(my.par[10,1]*(theta-my.par[10,2])))),
         p2.2 = (exp(my.par[2,1]*(theta-my.par[2,3]))/(1+exp(my.par[2,1]*(theta-my.par[2,3])))),
         p3.2 = (exp(my.par[3,1]*(theta-my.par[3,3]))/(1+exp(my.par[3,1]*(theta-my.par[3,3])))),
         p4.2 = (exp(my.par[4,1]*(theta-my.par[4,3]))/(1+exp(my.par[4,1]*(theta-my.par[4,3])))),
         p5.2 = (exp(my.par[5,1]*(theta-my.par[5,3]))/(1+exp(my.par[5,1]*(theta-my.par[5,3])))),
         p6.2 = (exp(my.par[6,1]*(theta-my.par[6,3]))/(1+exp(my.par[6,1]*(theta-my.par[6,3])))),
         p7.2 = (exp(my.par[7,1]*(theta-my.par[7,3]))/(1+exp(my.par[7,1]*(theta-my.par[7,3])))),
         p8.2 = (exp(my.par[8,1]*(theta-my.par[8,3]))/(1+exp(my.par[8,1]*(theta-my.par[8,3])))),
         p9.2 = (exp(my.par[9,1]*(theta-my.par[9,3]))/(1+exp(my.par[9,1]*(theta-my.par[9,3])))),
         p10.2 = (exp(my.par[10,1]*(theta-my.par[10,3]))/(1+exp(my.par[10,1]*(theta-my.par[10,3])))),
         es1 = p1.1, 
         es2 = p2.1 + p2.2, 
         es3 = p3.1 + p3.2, 
         es4 = p4.1 + p4.2, 
         es5 = p5.1 + p5.2, 
         es6 = p6.1 + p6.2, 
         es7 = p7.1 + p7.2, 
         es8 = p8.1 + p8.2, 
         es9 = p9.1 + p9.2, 
         es10 = p10.1 + p10.2, 
         i1 = my.par[1,1]^2 * (  ((1*(1-1)) - (p1.1*(1-p1.1)))^2/(1-p1.1) + ((p1.1*(1-p1.1)) - (0*(1-0)))^2/(p1.1-0)),
         i2 = my.par[2,1]^2 * (  ((1*(1-1)) - (p2.1*(1-p2.1)))^2/(1-p2.1) + ((p2.1*(1-p2.1))-(p2.2*(1-p2.2)))^2/(p2.1-p2.2) + ((p2.2*(1-p2.2))-(0*(1-0)))^2/(p2.2-0)),
         i3 = my.par[3,1]^2 * (  ((1*(1-1)) - (p3.1*(1-p3.1)))^2/(1-p3.1) + ((p3.1*(1-p3.1))-(p3.2*(1-p3.2)))^2/(p3.1-p3.2) + ((p3.2*(1-p3.2))-(0*(1-0)))^2/(p3.2-0)),
         i4 = my.par[4,1]^2 * (  ((1*(1-1)) - (p4.1*(1-p4.1)))^2/(1-p4.1) + ((p4.1*(1-p4.1))-(p4.2*(1-p4.2)))^2/(p4.1-p4.2) + ((p4.2*(1-p4.2))-(0*(1-0)))^2/(p4.2-0)),
         i5 = my.par[5,1]^2 * (  ((1*(1-1)) - (p5.1*(1-p5.1)))^2/(1-p5.1) + ((p5.1*(1-p5.1))-(p5.2*(1-p5.2)))^2/(p5.1-p5.2) + ((p5.2*(1-p5.2))-(0*(1-0)))^2/(p5.2-0)),
         i6 = my.par[6,1]^2 * (  ((1*(1-1)) - (p6.1*(1-p6.1)))^2/(1-p6.1) + ((p6.1*(1-p6.1))-(p6.2*(1-p6.2)))^2/(p6.1-p6.2) + ((p6.2*(1-p6.2))-(0*(1-0)))^2/(p6.2-0)),
         i7 = my.par[7,1]^2 * (  ((1*(1-1)) - (p7.1*(1-p7.1)))^2/(1-p7.1) + ((p7.1*(1-p7.1))-(p7.2*(1-p7.2)))^2/(p7.1-p7.2) + ((p7.2*(1-p7.2))-(0*(1-0)))^2/(p7.2-0)),
         i8 = my.par[8,1]^2 * (  ((1*(1-1)) - (p8.1*(1-p8.1)))^2/(1-p8.1) + ((p8.1*(1-p8.1))-(p8.2*(1-p8.2)))^2/(p8.1-p8.2) + ((p8.2*(1-p8.2))-(0*(1-0)))^2/(p8.2-0)),
         i9 = my.par[9,1]^2 * (  ((1*(1-1)) - (p9.1*(1-p9.1)))^2/(1-p9.1) + ((p9.1*(1-p9.1))-(p9.2*(1-p9.2)))^2/(p9.1-p9.2) + ((p9.2*(1-p9.2))-(0*(1-0)))^2/(p9.2-0)),
         i10 = my.par[10,1]^2 * (  ((1*(1-1)) - (p10.1*(1-p10.1)))^2/(1-p10.1) + ((p10.1*(1-p10.1))-(p10.2*(1-p10.2)))^2/(p10.1-p10.2) + ((p10.2*(1-p10.2))-(0*(1-0)))^2/(p10.2-0)),
         testscore = es1+es2+es3+es4+es5+es6+es7+es8+es9+es10,
         info = i1+i2+i3+i4+i5+i6+i7+i8+i9+i10)

```

## Plots for the polytomous model

```{r}

testscore <- drs.info.poly %>%
  select(theta, testscore) %>%
  rename(drsscore = testscore) %>%
  left_join(mdas.info.poly %>% 
              select(theta, testscore) %>%
              rename(mdasscore = testscore), by="theta") %>%
  left_join(cam.info.poly %>%
              select(theta, testscore) %>%
              rename(camscore = testscore), by="theta") %>%
  gather(test, score, 2:4)



ggplot(testscore, aes(theta, score, group=test, color=test)) +
  geom_line() +
  scale_color_brewer(palette = "Dark2", 
                     name = "Delirium Instrument",
                     breaks = c("drsscore", "mdasscore", "camscore"),
                     labels = c("DRS", "MDAS", "CAM-S")) + 
  xlab("Delirium Intensity") +
  ylab("Expected Total Score") +
  scale_y_continuous(breaks=seq(0,40,2)) +
  scale_x_continuous(breaks=seq(-4,8,1)) +
  ggtitle("Test Characteristic Curves (Polytomous CFA)")  

```



```{r}

testinfo <- drs.info.poly %>%
  select(theta, info) %>%
  rename(drsinfo = info) %>%
  left_join(mdas.info.poly %>% 
              select(theta, info) %>%
              rename(mdasinfo = info), by="theta") %>%
  left_join(cam.info.poly %>%
              select(theta, info) %>%
              rename(caminfo = info), by="theta") %>%
  gather(test, info, 2:4)



ggplot(testinfo, aes(theta, info, group=test, color=test)) +
  geom_line() +
  scale_color_brewer(palette = "Dark2", 
                     name = "Delirium Instrument",
                     breaks = c("drsinfo", "mdasinfo", "caminfo"),
                     labels = c("DRS", "MDAS", "CAM-S")) + 
  xlab("Delirium Intensity") +
  ylab("Information") +
  scale_y_continuous(breaks=seq(0,40,2)) +
  scale_x_continuous(breaks=seq(-4,8,1)) +
  ggtitle("Test Information Curves (Polytomous CFA)")  

```



