
### Figure 1

```{r, fig.height=10, eval=FALSE}
## The original figure

## Data for thresholds  
foo.drs<-  drs.par.poly %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.drs) %>%
  mutate(gr.order = recode(itemnum, "1=1; 10=2; 12=3; 11=4; 9=7; 6=8; 5=9; 13=10; 2=12; 7=15; 8=16; 3=13; 4=17;"),
         test = "DRS") 

foo.mdas<-  mdas.par.poly %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.mdas) %>%
  mutate(gr.order = recode(itemnum, "10=1; 5=2; 3=4; 4=5; 2=7; 6=8; 1=10.75; 7=12; 9=14; 8=13;"),
         gr.order = gr.order+.25,
         test = "MDAS",
         itemnum = itemnum+20) 

foo.cam<-  cam.par.poly %>%
  gather(B, est, 4:5) %>%
  arrange(itemnum, B) %>%
  rename(A = A.cam) %>%
  mutate(gr.order = recode(itemnum, "11=1; 2=2; 7=4; 1=6; 6=7; 3=8; 4=10.75; 5=11; 8=12; 9=15; 10=16; "),
         gr.order = gr.order+.5,
         test = "CAM",
         itemnum = itemnum+30) 


## Data for rug plots
## (using geom_point instead of geom_rug so that the instruments can be on their own line.)
fscores.drs <- getSavedata_Data("cfa-drs-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(DRS = f)

fscores.mdas <- getSavedata_Data("cfa-mdas-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(MDAS = f)

fscores.cam <- getSavedata_Data("cfa-cam-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(CAM = f)

fscores <- fscores.drs %>%
  left_join(fscores.mdas, by="recordid") %>%
  left_join(fscores.cam, by="recordid") %>%
  gather(test, fscore, 2:4) %>%
  mutate(fscore.y = ifelse(test=="DRS", 180,
                    ifelse(test=="MDAS", 182.5, 185)))

## locals for plotting locations
xmin <- -4
xmax <- 12
pos1 <- -4
pos2 <- 8.1
labsize <- 2
d1.loc <- 10      # Sleep
d2.loc <- 120     # Perceptual disturbance
d3.loc <- 130     # Delusions
d4.loc <- 170     # Lability
d5.loc <- 90      # Language
d6.loc <- 80      # Thought process
d7.loc <- 150     # Psychomotor agitation
d8.loc <- 160     # Psychomotor retardation
d9.loc <- 70      # Orientation
d10.loc <- 20     # Attention
d11.loc <- 40     # Short-term memory
d12.loc <- 30     # Long-term memory
d13.loc <- 100    # Visuospatial
m1.loc <- 110     # Awareness
m2.loc <- 72.5      # Disorientation
m3.loc <- 42.5      # Short-term memory
m4.loc <- 52.5      # Impaired digit span
m5.loc <- 22.5      # Attention
m6.loc <- 82.5      # Disorganized thinking
m7.loc <- 122.5     # Perceptual disturbance
m8.loc <- 132.5     # Delusions
m9.loc <- 142.5     # Psychomotor aggitation/retardation
m10.loc <- 12.5     # Sleep
c1.loc <- 65      # Acute change
c2.loc <- 25      # Inattention
c3.loc <- 85      # Disorganized thinking
c4.loc <- 112.5     # Level of consciousness (lethargic)
c5.loc <- 115     # Level of consciousness (vigilant)
c6.loc <- 75      # Disorientation
c7.loc <- 45      # Memory impairment
c8.loc <- 125     # Perceptual disturbance
c9.loc <- 155     # Psychomotor agitation
c10.loc <- 165    # Psychomotor retardation
c11.loc <- 15     # Sleep

sleep.loc <- mean(c(d1.loc, m10.loc, c11.loc))
attention.loc <- mean(c(d10.loc, m5.loc, c2.loc))
ltmemory.loc <- mean(c(d12.loc))
stmemory.loc <- mean(c(d11.loc, m3.loc, c7.loc))
digitspan.loc <- mean(c(m4.loc))
acute.loc <- mean(c(c1.loc))
orientation.loc <- mean(c(d9.loc, m2.loc, c6.loc))
disthinking.loc <- mean(c(d6.loc, m6.loc, c3.loc))
# thoughpro.loc <- mean(c())
language.loc <- mean(c(d5.loc))
visiospatial.loc <- mean(c(d13.loc))
percdis.loc <- mean(c(d2.loc, m7.loc, c8.loc))
psyaggret.loc <- mean(c(m9.loc))
psyagg.loc <- mean(c(d7.loc, c9.loc))
psyret.loc <- mean(c(d8.loc, c10.loc))
delusion.loc <- mean(c(d3.loc, m8.loc))
labaffect.loc <- mean(c(d4.loc))
awareness.loc <- mean(c(m1.loc, c4.loc, c5.loc))



plot_thresholds <-  foo.drs %>%
  bind_rows(foo.mdas) %>%
  bind_rows(foo.cam) %>%
  mutate(gr.order = gr.order*10) %>%
  ggplot(aes(x = est, y = gr.order, group=itemnum, color = test)) +
    geom_point(show.legend = FALSE) +
    geom_line(show.legend = FALSE) +
    geom_point(data=fscores, aes(x=fscore, y=fscore.y, group=NULL, color = test),
                                 shape = 124, alpha = .5, show.legend=FALSE) +
    scale_color_manual(values = c("#1b9e77", "#7570b3", "#e7298a"), 
                     name = "Delirium Instrument",
                     breaks = c("DRS", "MDAS", "CAM"),
                     labels = c("DRS-R-98", "MDAS", "CAM-S")) +
    scale_x_continuous("Delirium Intensity", limits = c(xmin, xmax), 
                       breaks = seq(-2, 8, by=2)) +
    scale_y_continuous(name=NULL, trans = "reverse") +
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_line(linetype = "dashed", color = "grey80"),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 17, ymax = 27, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 37, ymax = 47, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 57, ymax = 67, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 77, ymax = 87, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 97, ymax = 107, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 117, ymax = 127, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 137, ymax = 147, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 157, ymax = 167, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 177, ymax = 187, alpha = .2) +
    annotate("text", x = pos1, y = 5, hjust=0, label = "Item", 
             size = labsize, fontface =2) +
    annotate("text", x = pos2, y = 5, hjust=0, label = "Rated Item", 
             size = labsize, fontface =2) +
    annotate("text", x = pos1, y = d1.loc,  hjust=0, label = "DRS-R-98 1", 
             size = labsize) +
    annotate("text", x = pos1, y = d2.loc,  hjust=0, label = "DRS-R-98 2", 
             size = labsize) +
    annotate("text", x = pos1, y = d3.loc,  hjust=0, label = "DRS-R-98 3", 
             size = labsize) +
    annotate("text", x = pos1, y = d4.loc,  hjust=0, label = "DRS-R-98 4", 
             size = labsize) +
    annotate("text", x = pos1, y = d5.loc,  hjust=0, label = "DRS-R-98 5", 
             size = labsize) +
    annotate("text", x = pos1, y = d6.loc,  hjust=0, label = "DRS-R-98 6", 
             size = labsize) +
    annotate("text", x = pos1, y = d7.loc,  hjust=0, label = "DRS-R-98 7", 
             size = labsize) +
    annotate("text", x = pos1, y = d8.loc,  hjust=0, label = "DRS-R-98 8", 
             size = labsize) +
    annotate("text", x = pos1, y = d9.loc,  hjust=0, label = "DRS-R-98 9", 
             size = labsize) +
    annotate("text", x = pos1, y = d10.loc, hjust=0, label = "DRS-R-98 10", 
             size = labsize) +
    annotate("text", x = pos1, y = d11.loc, hjust=0, label = "DRS-R-98 11", 
             size = labsize) +
    annotate("text", x = pos1, y = d12.loc, hjust=0, label = "DRS-R-98 12", 
             size = labsize) +
    annotate("text", x = pos1, y = d13.loc, hjust=0, label = "DRS-R-98 13", 
             size = labsize) +
    annotate("text", x = pos1, y = m1.loc,  hjust=0, label = "MDAS 1", 
             size = labsize) +
    annotate("text", x = pos1, y = m2.loc,  hjust=0, label = "MDAS 2", 
             size = labsize) +
    annotate("text", x = pos1, y = m3.loc,  hjust=0, label = "MDAS 3", 
             size = labsize) +
    annotate("text", x = pos1, y = m4.loc,  hjust=0, label = "MDAS 4", 
             size = labsize) +
    annotate("text", x = pos1, y = m5.loc,  hjust=0, label = "MDAS 5", 
             size = labsize) +
    annotate("text", x = pos1, y = m6.loc,  hjust=0, label = "MDAS 6", 
             size = labsize) +
    annotate("text", x = pos1, y = m7.loc,  hjust=0, label = "MDAS 7", 
             size = labsize) +
    annotate("text", x = pos1, y = m8.loc,  hjust=0, label = "MDAS 8", 
             size = labsize) +
    annotate("text", x = pos1, y = m9.loc,  hjust=0, label = "MDAS 9", 
             size = labsize) +
    annotate("text", x = pos1, y = m10.loc, hjust=0, label = "MDAS 10", 
             size = labsize) +
    annotate("text", x = pos1, y = c1.loc, hjust=0, label = "CAM-S 1", 
             size = labsize) +
    annotate("text", x = pos1, y = c2.loc, hjust=0, label = "CAM-S 2", 
             size = labsize) +
    annotate("text", x = pos1, y = c3.loc, hjust=0, label = "CAM-S 3", 
             size = labsize) +
    annotate("text", x = pos1, y = c4.loc, hjust=0, label = "CAM-S 4 (lethargic)", 
             size = labsize) +
    annotate("text", x = pos1, y = c5.loc, hjust=0, label = "CAM-S 4 (vigilant)", 
             size = labsize) +
    annotate("text", x = pos1, y = c6.loc, hjust=0, label = "CAM-S 5", 
             size = labsize) +
    annotate("text", x = pos1, y = c7.loc, hjust=0, label = "CAM-S 6", 
             size = labsize) +
    annotate("text", x = pos1, y = c8.loc, hjust=0, label = "CAM-S 7", 
             size = labsize) +
    annotate("text", x = pos1, y = c9.loc, hjust=0, label = "CAM-S 8a", 
             size = labsize) +
    annotate("text", x = pos1, y = c10.loc, hjust=0, label = "CAM-S 8d", 
             size = labsize) +
    annotate("text", x = pos1, y = c11.loc, hjust=0, label = "CAM-S 9", 
             size = labsize) +
    annotate("text", x = pos2, y = sleep.loc, hjust=0, 
             label = "Sleep disturbance", size = labsize) +
    annotate("text", x = pos2, y = percdis.loc,  hjust=0, 
             label = "Perceptual disturbance", size = labsize) +
    annotate("text", x = pos2, y = delusion.loc, hjust=0, 
             label = "Delusions", size = labsize) +
    annotate("text", x = pos2, y = labaffect.loc, hjust=0, 
             label = "Labile affect", size = labsize) +
    annotate("text", x = pos2, y = language.loc,  hjust=0, 
             label = "Language impairment", size = labsize) +
    annotate("text", x = pos2, y = psyagg.loc, hjust=0, 
             label = "Psychomotor agitation", size = labsize) +
    annotate("text", x = pos2, y = psyret.loc, hjust=0, 
             label = "Psychomotor retardation", size = labsize) +
    annotate("text", x = pos2, y = orientation.loc,  hjust=0, 
             label = "Disorientation", size = labsize) +
    annotate("text", x = pos2, y = attention.loc,  hjust=0, 
             label = "Inattention", size = labsize) +
    annotate("text", x = pos2, y = stmemory.loc,  hjust=0, 
             label = "Short-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = ltmemory.loc,  hjust=0, 
             label = "Long-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = visiospatial.loc,  hjust=0, 
             label = "Visiospatial impairment", size = labsize) +
    annotate("text", x = pos2, y = psyaggret.loc, hjust=0, 
             label = "Psychomotor agitation or retardation", size = labsize) +
    annotate("text", x = pos2, y = digitspan.loc, hjust=0, 
             label = "Impaired Digit Span", size=labsize) +
    annotate("text", x = pos2, y = awareness.loc, hjust=0, 
             label = "Abnormal level of consciousness", size = labsize) +
    annotate("text", x = pos2, y = disthinking.loc, hjust=0, 
             label = "Disorganized thinking / \n Thought process abnormality", size = labsize) +
    annotate("text", x = pos2, y = acute.loc, hjust=0, 
             label = "Acute change", size = labsize) 
  
plot_thresholds
ggsave("Figure1.png", height = 20, units="cm")


```

```{r, fig.height=10}
# Removed the item number from the label
# Reversed the direction of the y-axis to original direction but kept the item ordering.  
# Added a line for a x-axis above the rug plot

## Data for thresholds  
foo.drs<-  drs.par.poly %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.drs) %>%
  mutate(gr.order = recode(itemnum, "1=17; 10=16; 12=15; 11=14; 9=11; 6=10; 5=9; 13=8; 2=6; 7=3; 8=2; 3=5; 4=1;"),
         test = "DRS") 

foo.mdas<-  mdas.par.poly %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.mdas) %>%
  mutate(gr.order = recode(itemnum, "10=17; 5=16; 3=14; 4=13; 2=11; 6=10; 1=7.25; 7=6; 9=4; 8=5;"),
         gr.order = gr.order-.25,
         test = "MDAS",
         itemnum = itemnum+20) 

foo.cam<-  cam.par.poly %>%
  gather(B, est, 4:5) %>%
  arrange(itemnum, B) %>%
  rename(A = A.cam) %>%
  mutate(gr.order = recode(itemnum, "11=17; 2=16; 7=14; 1=12; 6=11; 3=10; 4=7.25; 5=7; 8=6; 9=3; 10=2; "),
         gr.order = gr.order-.5,
         test = "CAM",
         itemnum = itemnum+30) 


## Data for rug plots
## (using geom_point instead of geom_rug so that the instruments can be on their own line.)
fscores.drs <- getSavedata_Data("cfa-drs-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(DRS = f)

fscores.mdas <- getSavedata_Data("cfa-mdas-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(MDAS = f)

fscores.cam <- getSavedata_Data("cfa-cam-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(CAM = f)

r1.loc <- -5
r2.loc <- -7.5
r3.loc <- -10

fscores <- fscores.drs %>%
  left_join(fscores.mdas, by="recordid") %>%
  left_join(fscores.cam, by="recordid") %>%
  gather(test, fscore, 2:4) %>%
  mutate(fscore.y = ifelse(test=="DRS", r1.loc,
                    ifelse(test=="MDAS", r2.loc, r3.loc)))

## locals for plotting locations
xmin <- -4
xmax <- 12
pos1 <- -4
pos2 <- 8.1
labsize <- 2
d1.loc <- 170      # Sleep
d2.loc <- 60     # Perceptual disturbance
d3.loc <- 50     # Delusions
d4.loc <- 10     # Lability
d5.loc <- 90      # Language
d6.loc <- 100      # Thought process
d7.loc <- 30     # Psychomotor agitation
d8.loc <- 20     # Psychomotor retardation
d9.loc <- 110      # Orientation
d10.loc <- 160     # Attention
d11.loc <- 140     # Short-term memory
d12.loc <- 150     # Long-term memory
d13.loc <- 80    # Visuospatial
m1.loc <- 70     # Awareness
m2.loc <- 107.5      # Disorientation
m3.loc <- 137.5      # Short-term memory
m4.loc <- 127.5      # Impaired digit span
m5.loc <- 157.5      # Attention
m6.loc <- 97.5      # Disorganized thinking
m7.loc <- 57.5     # Perceptual disturbance
m8.loc <- 47.5     # Delusions
m9.loc <- 37.5     # Psychomotor aggitation/retardation
m10.loc <- 167.5     # Sleep
c1.loc <- 115      # Acute change
c2.loc <- 155      # Inattention
c3.loc <- 95      # Disorganized thinking
c4.loc <- 67.5     # Level of consciousness (lethargic)
c5.loc <- 65     # Level of consciousness (vigilant)
c6.loc <- 105      # Disorientation
c7.loc <- 135      # Memory impairment
c8.loc <- 55     # Perceptual disturbance
c9.loc <- 25     # Psychomotor agitation
c10.loc <- 15    # Psychomotor retardation
c11.loc <- 165     # Sleep

sleep.loc <- mean(c(d1.loc, m10.loc, c11.loc))
attention.loc <- mean(c(d10.loc, m5.loc, c2.loc))
ltmemory.loc <- mean(c(d12.loc))
stmemory.loc <- mean(c(d11.loc, m3.loc, c7.loc))
digitspan.loc <- mean(c(m4.loc))
acute.loc <- mean(c(c1.loc))
orientation.loc <- mean(c(d9.loc, m2.loc, c6.loc))
disthinking.loc <- mean(c(d6.loc, m6.loc, c3.loc))
# thoughpro.loc <- mean(c())
language.loc <- mean(c(d5.loc))
visiospatial.loc <- mean(c(d13.loc))
percdis.loc <- mean(c(d2.loc, m7.loc, c8.loc))
psyaggret.loc <- mean(c(m9.loc))
psyagg.loc <- mean(c(d7.loc, c9.loc))
psyret.loc <- mean(c(d8.loc, c10.loc))
delusion.loc <- mean(c(d3.loc, m8.loc))
labaffect.loc <- mean(c(d4.loc))
awareness.loc <- mean(c(m1.loc, c4.loc, c5.loc))
rug.loc <- mean(c(r1.loc, r2.loc, r3.loc))

plot_thresholds <-  foo.drs %>%
  bind_rows(foo.mdas) %>%
  bind_rows(foo.cam) %>%
  mutate(gr.order = gr.order*10) %>%
  ggplot(aes(x = est, y = gr.order, group=itemnum, color = test)) +
    geom_point(show.legend = FALSE) +
    geom_line(show.legend = FALSE) +
    geom_point(data=fscores, aes(x=fscore, y=fscore.y, group=NULL, color = test),
                                 shape = 124, alpha = .5, show.legend=FALSE) +
    scale_color_manual(values = c("#1b9e77", "#7570b3", "#e7298a"), 
                     name = "Delirium Instrument",
                     breaks = c("DRS", "MDAS", "CAM"),
                     labels = c("DRS-R-98", "MDAS", "CAM-S")) +
    scale_x_continuous("Delirium Intensity", limits = c(xmin, xmax), 
                       breaks = seq(-2, 8, by=2)) +
    scale_y_continuous(name=NULL) +
    geom_vline(xintercept = seq(-2, 8, by=2), linetype = "dashed", color = "grey80") +
    geom_segment(aes(x= xmin ,xend= xmax, y= 2.5, yend= 2.5), color = "black") + 
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 162.5, ymax = 172.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 142.5, ymax = 152.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 122.5, ymax = 132.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 102.5, ymax = 112.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  82.5, ymax =  92.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  62.5, ymax =  72.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  42.5, ymax =  52.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  22.5, ymax =  32.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =   2.5, ymax =  12.5, alpha = .2) +
    annotate("text", x = pos1, y = 175, hjust=0, label = "Instrument", 
             size = labsize, fontface =2) +
    annotate("text", x = pos2, y = 175, hjust=0, label = "Rated Item", 
             size = labsize, fontface =2) +
    annotate("text", x = pos1, y = r1.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = r2.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = r3.loc,  hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = d1.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d2.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d3.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d4.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d5.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d6.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d7.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d8.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d9.loc,  hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d10.loc, hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d11.loc, hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d12.loc, hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = d13.loc, hjust=0, label = "DRS-R-98", 
             size = labsize) +
    annotate("text", x = pos1, y = m1.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m2.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m3.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m4.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m5.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m6.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m7.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m8.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m9.loc,  hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = m10.loc, hjust=0, label = "MDAS", 
             size = labsize) +
    annotate("text", x = pos1, y = c1.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c2.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c3.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c4.loc, hjust=0, label = "CAM-S (lethargic)", 
             size = labsize) +
    annotate("text", x = pos1, y = c5.loc, hjust=0, label = "CAM-S (vigilant)", 
             size = labsize) +
    annotate("text", x = pos1, y = c6.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c7.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c8.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c9.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c10.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos1, y = c11.loc, hjust=0, label = "CAM-S", 
             size = labsize) +
    annotate("text", x = pos2, y = sleep.loc, hjust=0, 
             label = "Sleep disturbance", size = labsize) +
    annotate("text", x = pos2, y = percdis.loc,  hjust=0, 
             label = "Perceptual disturbance", size = labsize) +
    annotate("text", x = pos2, y = delusion.loc, hjust=0, 
             label = "Delusions", size = labsize) +
    annotate("text", x = pos2, y = labaffect.loc, hjust=0, 
             label = "Labile affect", size = labsize) +
    annotate("text", x = pos2, y = language.loc,  hjust=0, 
             label = "Language impairment", size = labsize) +
    annotate("text", x = pos2, y = psyagg.loc, hjust=0, 
             label = "Psychomotor agitation", size = labsize) +
    annotate("text", x = pos2, y = psyret.loc, hjust=0, 
             label = "Psychomotor retardation", size = labsize) +
    annotate("text", x = pos2, y = orientation.loc,  hjust=0, 
             label = "Disorientation", size = labsize) +
    annotate("text", x = pos2, y = attention.loc,  hjust=0, 
             label = "Inattention", size = labsize) +
    annotate("text", x = pos2, y = stmemory.loc,  hjust=0, 
             label = "Short-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = ltmemory.loc,  hjust=0, 
             label = "Long-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = visiospatial.loc,  hjust=0, 
             label = "Visiospatial impairment", size = labsize) +
    annotate("text", x = pos2, y = psyaggret.loc, hjust=0, 
             label = "Psychomotor agitation or retardation", size = labsize) +
    annotate("text", x = pos2, y = digitspan.loc, hjust=0, 
             label = "Impaired Digit Span", size=labsize) +
    annotate("text", x = pos2, y = awareness.loc, hjust=0, 
             label = "Abnormal level of consciousness", size = labsize) +
    annotate("text", x = pos2, y = disthinking.loc, hjust=0, 
             label = "Disorganized thinking / \n Thought process abnormality", size = labsize) +
    annotate("text", x = pos2, y = acute.loc, hjust=0, 
             label = "Acute change", size = labsize) +
    annotate("text", x = pos2, y = rug.loc, hjust=0, 
             label = "Distribution of \n Delirium Intensity", size = labsize) 
  
plot_thresholds
ggsave("Figure1.png", height = 20, units="cm")

```

```{r, fig.height=10}
# Removed the item number from the label
# Reversed the direction of the y-axis to original direction but kept the item ordering.  
# Added a line for a x-axis above the rug plot

## Data for thresholds  
foo.drs<-  drs.par.poly %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.drs) %>%
  mutate(gr.order = recode(itemnum, "1=17; 10=16; 12=15; 11=14; 9=11; 6=10; 5=9; 13=8; 2=6; 7=3; 8=2; 3=5; 4=1;"),
         test = "DRS") 

foo.mdas<-  mdas.par.poly %>%
  gather(B, est, 4:6) %>%
  arrange(itemnum, B) %>%
  rename(A = A.mdas) %>%
  mutate(gr.order = recode(itemnum, "10=17; 5=16; 3=14; 4=13; 2=11; 6=10; 1=7.25; 7=6; 9=4; 8=5;"),
         gr.order = gr.order-.25,
         test = "MDAS",
         itemnum = itemnum+20) 

foo.cam<-  cam.par.poly %>%
  gather(B, est, 4:5) %>%
  arrange(itemnum, B) %>%
  rename(A = A.cam) %>%
  mutate(gr.order = recode(itemnum, "11=17; 2=16; 7=14; 1=12; 6=11; 3=10; 4=7.25; 5=7; 8=6; 9=3; 10=2; "),
         gr.order = gr.order-.5,
         test = "CAM",
         itemnum = itemnum+30) 


## Data for rug plots
## (using geom_point instead of geom_rug so that the instruments can be on their own line.)
fscores.drs <- getSavedata_Data("cfa-drs-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(DRS = f)

fscores.mdas <- getSavedata_Data("cfa-mdas-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(MDAS = f)

fscores.cam <- getSavedata_Data("cfa-cam-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(CAM = f)

r1.loc <- -5
r2.loc <- -7.5
r3.loc <- -10

fscores <- fscores.drs %>%
  left_join(fscores.mdas, by="recordid") %>%
  left_join(fscores.cam, by="recordid") %>%
  gather(test, fscore, 2:4) %>%
  mutate(fscore.y = ifelse(test=="DRS", r1.loc,
                    ifelse(test=="MDAS", r2.loc, r3.loc)))

## locals for plotting locations
xmin <- -2.5
xmax <- 12
pos1 <- -4
pos2 <- 8.1
labsize <- 2
d1.loc <- 170      # Sleep
d2.loc <- 60     # Perceptual disturbance
d3.loc <- 50     # Delusions
d4.loc <- 10     # Lability
d5.loc <- 90      # Language
d6.loc <- 100      # Thought process
d7.loc <- 30     # Psychomotor agitation
d8.loc <- 20     # Psychomotor retardation
d9.loc <- 110      # Orientation
d10.loc <- 160     # Attention
d11.loc <- 140     # Short-term memory
d12.loc <- 150     # Long-term memory
d13.loc <- 80    # Visuospatial
m1.loc <- 70     # Awareness
m2.loc <- 107.5      # Disorientation
m3.loc <- 137.5      # Short-term memory
m4.loc <- 127.5      # Impaired digit span
m5.loc <- 157.5      # Attention
m6.loc <- 97.5      # Disorganized thinking
m7.loc <- 57.5     # Perceptual disturbance
m8.loc <- 47.5     # Delusions
m9.loc <- 37.5     # Psychomotor aggitation/retardation
m10.loc <- 167.5     # Sleep
c1.loc <- 115      # Acute change
c2.loc <- 155      # Inattention
c3.loc <- 95      # Disorganized thinking
c4.loc <- 67.5     # Level of consciousness (lethargic)
c5.loc <- 65     # Level of consciousness (vigilant)
c6.loc <- 105      # Disorientation
c7.loc <- 135      # Memory impairment
c8.loc <- 55     # Perceptual disturbance
c9.loc <- 25     # Psychomotor agitation
c10.loc <- 15    # Psychomotor retardation
c11.loc <- 165     # Sleep

sleep.loc <- mean(c(d1.loc, m10.loc, c11.loc))
attention.loc <- mean(c(d10.loc, m5.loc, c2.loc))
ltmemory.loc <- mean(c(d12.loc))
stmemory.loc <- mean(c(d11.loc, m3.loc, c7.loc))
digitspan.loc <- mean(c(m4.loc))
acute.loc <- mean(c(c1.loc))
orientation.loc <- mean(c(d9.loc, m2.loc, c6.loc))
disthinking.loc <- mean(c(d6.loc, m6.loc, c3.loc))
# thoughpro.loc <- mean(c())
language.loc <- mean(c(d5.loc))
visiospatial.loc <- mean(c(d13.loc))
percdis.loc <- mean(c(d2.loc, m7.loc, c8.loc))
psyaggret.loc <- mean(c(m9.loc))
psyagg.loc <- mean(c(d7.loc, c9.loc))
psyret.loc <- mean(c(d8.loc, c10.loc))
delusion.loc <- mean(c(d3.loc, m8.loc))
labaffect.loc <- mean(c(d4.loc))
awareness.loc <- mean(c(m1.loc, c4.loc, c5.loc))
rug.loc <- mean(c(r1.loc, r2.loc, r3.loc))

plot_thresholds <-  foo.drs %>%
  bind_rows(foo.mdas) %>%
  bind_rows(foo.cam) %>%
  mutate(gr.order = gr.order*10) %>%
  ggplot(aes(x = est, y = gr.order, group=itemnum, color = test)) +
    geom_point(show.legend = TRUE) +
    geom_line(show.legend = TRUE) +
    geom_point(data=fscores, aes(x=fscore, y=fscore.y, group=NULL, color = test),
                                 shape = 124, alpha = .5, show.legend=FALSE) +
    scale_color_manual(values = c("#1b9e77", "#7570b3", "#e7298a"), 
                     name = "Delirium Instrument:",
                     breaks = c("DRS", "MDAS", "CAM"),
                     labels = c("DRS-R-98", "MDAS", "CAM-S")) +
    scale_x_continuous("Delirium Intensity", limits = c(xmin, xmax), 
                       breaks = seq(-2, 8, by=2)) +
    scale_y_continuous(name=NULL) +
    geom_vline(xintercept = seq(-2, 8, by=2), linetype = "dashed", color = "grey80") +
    geom_segment(aes(x= xmin ,xend= xmax, y= 2.5, yend= 2.5), color = "black") + 
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.position = "bottom") +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 162.5, ymax = 172.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 142.5, ymax = 152.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 122.5, ymax = 132.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin = 102.5, ymax = 112.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  82.5, ymax =  92.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  62.5, ymax =  72.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  42.5, ymax =  52.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =  22.5, ymax =  32.5, alpha = .2) +
    annotate("rect", xmin = xmin, xmax = xmax, ymin =   2.5, ymax =  12.5, alpha = .2) +
    annotate("text", x = pos2, y = 175, hjust=0, label = "Rated Item", 
             size = labsize, fontface =2) +
    annotate("text", x = pos2, y = sleep.loc, hjust=0, 
             label = "Sleep disturbance", size = labsize) +
    annotate("text", x = pos2, y = percdis.loc,  hjust=0, 
             label = "Perceptual disturbance", size = labsize) +
    annotate("text", x = pos2, y = delusion.loc, hjust=0, 
             label = "Delusions", size = labsize) +
    annotate("text", x = pos2, y = labaffect.loc, hjust=0, 
             label = "Labile affect", size = labsize) +
    annotate("text", x = pos2, y = language.loc,  hjust=0, 
             label = "Language impairment", size = labsize) +
    annotate("text", x = pos2, y = psyagg.loc, hjust=0, 
             label = "Psychomotor agitation", size = labsize) +
    annotate("text", x = pos2, y = psyret.loc, hjust=0, 
             label = "Psychomotor retardation", size = labsize) +
    annotate("text", x = pos2, y = orientation.loc,  hjust=0, 
             label = "Disorientation", size = labsize) +
    annotate("text", x = pos2, y = attention.loc,  hjust=0, 
             label = "Inattention", size = labsize) +
    annotate("text", x = pos2, y = stmemory.loc,  hjust=0, 
             label = "Short-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = ltmemory.loc,  hjust=0, 
             label = "Long-term memory problem", size = labsize) +
    annotate("text", x = pos2, y = visiospatial.loc,  hjust=0, 
             label = "Visiospatial impairment", size = labsize) +
    annotate("text", x = pos2, y = psyaggret.loc, hjust=0, 
             label = "Psychomotor agitation or retardation", size = labsize) +
    annotate("text", x = pos2, y = digitspan.loc, hjust=0, 
             label = "Impaired Digit Span", size=labsize) +
    annotate("text", x = pos2, y = awareness.loc, hjust=0, 
             label = "Abnormal level of consciousness", size = labsize) +
    annotate("text", x = pos2, y = disthinking.loc, hjust=0, 
             label = "Disorganized thinking / \n Thought process abnormality", size = labsize) +
    annotate("text", x = pos2, y = acute.loc, hjust=0, 
             label = "Acute change", size = labsize) +
    annotate("text", x = pos2, y = rug.loc, hjust=0, 
             label = "Distribution of \n Delirium Intensity", size = labsize) 
  
plot_thresholds
ggsave("Figure1a.png", height = 20, units="cm")

```

