
### Figure 2

```{r, eval=FALSE}

# testinfo <- drs.info.poly %>%
#   select(theta, info) %>%
#   rename(drsinfo = info) %>%
#   left_join(mdas.info.poly %>% 
#               select(theta, info) %>%
#               rename(mdasinfo = info), by="theta") %>%
#   left_join(camlf.info.poly %>%
#               select(theta, info) %>%
#               rename(camlfinfo = info), by="theta") %>%
#   left_join(camsf.info.poly %>%
#               select(theta, info) %>%
#               rename(camsfinfo = info), by="theta") %>%
#   gather(test, info, 2:5)
# 
# ggplot(testinfo, aes(theta, info, group=test, color=test)) +
#   geom_line() +
#   scale_color_brewer(palette = "Dark2", 
#                      name = "Delirium Instrument",
#                      breaks = c("drsinfo", "mdasinfo", "camlfinfo", "camsfinfo"),
#                      labels = c("DRS", "MDAS", "CAM-S LF", "CAM-S SF")) + 
#   scale_y_continuous("Information", breaks=seq(0, 16, 2)) +
#   scale_x_continuous("Delirium Intensity", breaks=seq(-4, 8, 1)) +
#   ggtitle("Test Information Curves")  +
#   theme_doug()

# Figure is from 012-polytomous-test-characteristic-curve.Rmd
plot_test_information
ggsave("Figure2.png")



```


```{r, eval=FALSE}
plot_test_reliability 
ggsave("Figure2a.png")
```

```{r}
## Adding a rug plot to the Information/Reliability plots
## Data for rug plots

fscores.drs <- getSavedata_Data("cfa-drs-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(DRS = f)

fscores.mdas <- getSavedata_Data("cfa-mdas-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(MDAS = f)

fscores.cam <- getSavedata_Data("cfa-cam-3-1.out") %>%
  setNames(tolower(names(.))) %>%
  select(recordid, f) %>%
  rename(CAM = f)

fscores <- fscores.drs %>%
  left_join(fscores.mdas, by="recordid") %>%
  left_join(fscores.cam, by="recordid") %>%
  gather(test, fscore, 2:4) 

plot_test_information +
  geom_rug(data = fscores, aes(x=fscore), inherit.aes = F, alpha=0.1)
ggsave("Figure2.png")

plot_test_information +
  geom_rug(data = fscores, aes(x=fscore), inherit.aes = F, alpha=0.1) + 
  scale_y_continuous("Reliability", breaks=seq(0,12,2), labels = c("", "0.50", "0.75", "0.83", "0.88", "0.90", "0.92"))
ggsave("Figure2a.png")

plot_test_reliability +
  geom_rug(data = fscores, aes(x=fscore), inherit.aes = F, alpha=0.1)
ggsave("Figure2b.png")

```

