
### Figure A1: Nomogram
(The nomogram figures aren't turning out well, so the tables they are based on are being provided.)

```{r}

testscore <- drs.info.poly %>%
  select(theta, testscore) %>%
  rename(drsscore = testscore) %>%
  left_join(mdas.info.poly %>% 
              select(theta, testscore) %>%
              rename(mdasscore = testscore), by="theta") %>%
  left_join(cam.info.poly %>%
              select(theta, testscore) %>%
              rename(camscore = testscore), by="theta") 
```

#### Table A1a: CAM-S table
```{r}
testscore %>%
  mutate(goo.cam = round(camscore)) %>%
  group_by(goo.cam) %>%
  mutate(hoo.cam = abs(camscore-goo.cam),
         ioo.cam = min(hoo.cam)) %>%
  filter(hoo.cam==ioo.cam) %>%
  select(-hoo.cam, -ioo.cam, -camscore, -theta) %>%
  mutate(score = goo.cam) %>%
  select(goo.cam, mdasscore, drsscore) %>%
  kable(digits = c(0, 1, 1), col.names= c("CAM-S", "MDAS", "DRS"), caption = "CAM-S to MDAS and DRS") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center")
```


#### Table A1b: MDAS table
```{r}
testscore %>%
  mutate(goo.mdas = round(mdasscore)) %>%
  group_by(goo.mdas) %>%
  mutate(hoo.mdas = abs(mdasscore-goo.mdas),
         ioo.mdas = min(hoo.mdas)) %>%
  filter(hoo.mdas==ioo.mdas) %>%
  select(-hoo.mdas, -ioo.mdas, -mdasscore, -theta) %>%
  mutate(score = goo.mdas) %>%
  select(goo.mdas, camscore, drsscore) %>% 
  kable(digits = c(0, 1, 1), col.names = c("MDAS", "CAM-S", "DRS"), caption = "MDAS to CAM-S and DRS") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center")
```

#### Table A1c: DRS table
```{r}
testscore %>%
  mutate(goo.drs = round(drsscore)) %>%
  group_by(goo.drs) %>%
  mutate(hoo.drs = abs(drsscore-goo.drs),
         ioo.drs = min(hoo.drs)) %>%
  filter(hoo.drs==ioo.drs) %>%
  select(-hoo.drs, -ioo.drs, -drsscore, -theta) %>%
  mutate(score = goo.drs) %>%
  select(goo.drs, camscore, mdasscore) %>%
  kable(digits = c(0, 1, 1), col.names = c("DRS", "CAM-S", "MDAS"), caption = "DRS to CAM-S and MDAS") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center")
```


#### Figure A1a: CAM-S nomogram

```{r, fig.height=8}

foo <- testscore %>%
  mutate(goo.cam = round(camscore)) %>%
  group_by(goo.cam) %>%
  mutate(hoo.cam = abs(camscore-goo.cam),
         ioo.cam = min(hoo.cam)) %>%
  filter(hoo.cam==ioo.cam) %>%
  select(-hoo.cam, -ioo.cam, -camscore, -theta) %>%
  mutate(score = goo.cam) %>%
  gather(test, value, 1:3) %>%
  mutate(value.lab = round(value, 0),
         labelx = ifelse(test=="drsscore", 1,
                  ifelse(test=="mdasscore", 3, 2 )),
         dup = 0) %>%
  arrange(score) 

foo %>%
  filter(test=="goo.cam") %>%
  mutate(dup = 1) %>%
  bind_rows(foo) %>%
  arrange(score, labelx, dup) %>%
  mutate(pointx = ifelse(labelx==3, 2.9,
                  ifelse(labelx==1, 1.1,
                  ifelse(labelx==2 & dup==0, 1.9, 2.1))),
         tmp = ifelse(labelx==1 & dup==0, 0,
                ifelse(labelx==2 & dup==0, 0,
                ifelse(labelx==2 & dup==1, 1, 1))),
         g.new = factor(paste(score, tmp))) %>%
  select(-test, -value, -dup) %>%
  ggplot(aes(x=pointx, y=value.lab, group=g.new, label = value.lab)) +
    geom_line() +
    geom_label(aes(x=labelx), label.size = NA) +
    scale_x_discrete("Delirium Instrument", 
                     labels = c("drsscore" = "DRS", 
                                "goo.cam"= "CAM-S", 
                                "mdasscore"="MDAS"),
                     limits = c("drsscore", "goo.cam", "mdasscore")) +
    scale_y_continuous("Value", limits = c(0, 36), breaks = seq(0, 36, by = 2)) +
    ggtitle("Nomogram linking CAM-S with DRS and MDAS") +
    theme_doug() +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          plot.title = element_text(hjust = .5))  
  
ggsave("nomogram-cam.pdf", height = 20, units="cm")

```

#### Figure A1b: MDAS nomogram
```{r, fig.height=8}

foo <- testscore %>%
  mutate(goo.mdas = round(mdasscore)) %>%
  group_by(goo.mdas) %>%
  mutate(hoo.mdas = abs(mdasscore-goo.mdas),
         ioo.mdas = min(hoo.mdas)) %>%
  filter(hoo.mdas==ioo.mdas) %>%
  select(-hoo.mdas, -ioo.mdas, -mdasscore, -theta) %>%
  mutate(score = goo.mdas) %>%
  gather(test, value, 1:3) %>%
  mutate(value.lab = round(value, 0),
         labelx = ifelse(test=="drsscore", 3,
                  ifelse(test=="camscore", 1, 2 )),
         dup = 0) %>%
  arrange(score) 

foo %>%
  filter(test=="goo.mdas") %>%
  mutate(dup = 1) %>%
  bind_rows(foo) %>%
  arrange(score, labelx, dup) %>%
  mutate(pointx = ifelse(labelx==3, 2.9,
                  ifelse(labelx==1, 1.1,
                  ifelse(labelx==2 & dup==0, 1.9, 2.1))),
         tmp = ifelse(labelx==1 & dup==0, 0,
                ifelse(labelx==2 & dup==0, 0,
                ifelse(labelx==2 & dup==1, 1, 1))),
         g.new = factor(paste(score, tmp))) %>%
  select(-test, -value, -dup) %>%
  ggplot(aes(x=pointx, y=value.lab, group=g.new, label = value.lab)) +
    geom_line() +
    geom_label(aes(x=labelx), label.size = NA) +
    scale_x_discrete("Delirium Instrument", 
                     labels = c("drsscore" = "DRS", 
                                "goo.mdas"= "MDAS", 
                                "camscore"="CAM-S"), 
                     limits = c("camscore", "goo.mdas", "drsscore")) +
    scale_y_continuous("Value", limits = c(0, 36), breaks = seq(0, 36, by = 2)) +
    ggtitle("Nomogram linking MDAS with DRS and CAM-S") +
    theme_doug() +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          plot.title = element_text(hjust = .5))  
  
ggsave("nomogram-mdas.pdf", height = 20, units="cm")
```

#### Figure A1c: DRS nomogram
```{r, fig.height=8}
foo <- testscore %>%
  mutate(goo.drs = round(drsscore)) %>%
  group_by(goo.drs) %>%
  mutate(hoo.drs = abs(drsscore-goo.drs),
         ioo.drs = min(hoo.drs)) %>%
  filter(hoo.drs==ioo.drs) %>%
  select(-hoo.drs, -ioo.drs, -drsscore, -theta) %>%
  mutate(score = goo.drs) %>%
  gather(test, value, 1:3) %>%
  mutate(value.lab = round(value, 0),
         labelx = ifelse(test=="mdasscore", 3,
                  ifelse(test=="camscore", 1, 2 )),
         dup = 0) %>%
  arrange(score) 

foo %>%
  filter(test=="goo.drs") %>%
  mutate(dup = 1) %>%
  bind_rows(foo) %>%
  arrange(score, labelx, dup) %>%
  mutate(pointx = ifelse(labelx==3, 2.9,
                  ifelse(labelx==1, 1.1,
                  ifelse(labelx==2 & dup==0, 1.9, 2.1))),
         tmp = ifelse(labelx==1 & dup==0, 0,
                ifelse(labelx==2 & dup==0, 0,
                ifelse(labelx==2 & dup==1, 1, 1))),
         g.new = factor(paste(score, tmp))) %>%
  select(-test, -value, -dup) %>%
  ggplot(aes(x=pointx, y=value.lab, group=g.new, label = value.lab)) +
    geom_line() +
    geom_label(aes(x=labelx), label.size = NA) +
    scale_x_discrete("Delirium Instrument", 
                     labels = c("mdasscore" = "MDAS", 
                                "goo.drs"= "DRS", 
                                "camscore"="CAM-S"), 
                     limits = c("camscore", "goo.drs", "mdasscore")) +
    scale_y_continuous("Value", limits = c(0, 36), breaks = seq(0, 36, by = 2)) +
    ggtitle("Nomogram linking DRS with MDAS and CAM-S") +
    theme_doug() +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          plot.title = element_text(hjust = .5))
  

ggsave("nomogram-drs.pdf", height = 30, units="cm")

```

