---
title: "BASIL/NIDUS Harmonization Paper"
author: "Doug Tommet, Rich Jones"
date: '`r Sys.Date()`'
output:
  html_document:
    keep_md: yes
    theme: cerulean
    toc: yes
    toc_float: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

options(knitr.table.format = "html") 
set.seed(2017)

```

```{r, child="000-opening-summary.Rmd"}
```

# Report

```{r, child="001-libraries and functions.Rmd"}
```

```{r, child="002-read data.Rmd"}
```

```{r, child="003-recode data.Rmd"}
```


```{r, child="004-descriptive-stats-for-items.Rmd"}
```


```{r, child="005a-fit-cfa-models.Rmd"}
```

```{r, child="006-equating-parameters.Rmd"}
 
```

```{r, child="008-item-characteristic-plots.Rmd"}
 
```

```{r, child="009-density-plots.Rmd"}
 
```

```{r, child="010-test-characteristic-curve.Rmd"}
 
```

```{r, child="011-fit-cfa-model-multiple-categories.Rmd"}
 
```

```{r, child="012-polytomous-test-characteristic-curve.Rmd"}
 
```

# For the manuscript
This section contains tables/figures for the manuscript.
```{r, child="021-table1.Rmd"}
 
```

```{r, child="022-table2.Rmd"}
 
```

```{r, child="023-table3.Rmd"}
 
```

```{r, child="024-figure1.Rmd"}
 
```

```{r, child="025-figure2.Rmd"}
 
```

```{r, child="026-figure3.Rmd"}
 
```

```{r, child="027-figure4.Rmd"}
 
```

# For the appendix
This section contains tables/figures for the appendix.
```{r, child="029-figure5.Rmd"}
 
```

```{r, child="040-bootstrap-item-parameters.Rmd", eval=TRUE}
 
```

# Sensitivity/Supplemental Analyses
This section contains analyses that are more exploratory in nature, and could be supplemental to the manuscript.
```{r, child="035-first-thresholds.Rmd"}
 
```

# For Rich & Alden
```{r, child="050-figures-for-RNJ-ALG.Rmd"}

```


